unit PascalCommon.MetricsTests;

{$mode delphi}{$H+}

{ GENERATED FILE — produced by tools/gen_fpc_mirror.py from
  tests/Unit/PascalCommon.MetricsTests.pas (DUnitX). Do not edit by hand: edit the DUnitX
  master and run the script again. }

{ Tests for PascalCommon.Metrics: each instrument's arithmetic and what it
  ignores, histogram bucket placement (bounds are inclusive), series by label
  values, the registry's get-or-create rules and validation, the
  OpenTelemetry-to-Prometheus name conversion, float text, the whole
  Prometheus exposition byte by byte (HELP/TYPE, label escaping, cumulative
  buckets, _sum, _count), and exact totals when several threads register and
  record at once.

  The threaded test waits on TThread.WaitFor, not on a Sleep. Each test uses
  its own TPcMetricRegistry; PcMetrics, the global one, is only checked to
  exist.

  DUnitX master: the FPCUnit mirror in tests/Unit/fpc is generated by
  tools/gen_fpc_mirror.py. }

interface

uses
  fpcunit, testregistry,
  Classes,
  SysUtils,
  Math,
  PascalCommon.Metrics;

type
  TMetricsTests = class(TTestCase)
  published
    procedure Counter_AddsAndIgnoresNegativeAndNaN;
    procedure UpDownCounter_GoesBothWays;
    procedure Gauge_SetsAndIgnoresNaN;
    procedure Histogram_BoundsAreInclusive;
    procedure Histogram_WithoutBounds_HasOnlyTheInfBucket;
    procedure Labels_SameValues_SameSeries;
    procedure Labels_WrongCount_Raises;
    procedure Labels_FamilyMethods_NeedNoLabels;
    procedure Snapshot_InCreationOrder;
    procedure Registry_SameDefinition_ReturnsTheSameMetric;
    procedure Registry_OtherDefinition_Raises;
    procedure Registry_InvalidDefinitions_Raise;
    procedure Registry_Metrics_InRegistrationOrder;
    procedure PrometheusName_FromOpenTelemetry;
    procedure PrometheusFloat_Text;
    procedure PrometheusText_ByteByByte;
    procedure PrometheusText_EmptyRegistry;
    procedure Threads_RegisterAndRecord_ExactTotals;
    procedure GlobalRegistry_Exists;
  end;

implementation

const
  THREAD_COUNT = 4;
  OPS_PER_THREAD = 5000;

type
  TRecorderThread = class(TThread)
  private
    FRegistry: TPcMetricRegistry;
    FIndex: Integer;
  protected
    procedure Execute; override;
  public
    Error: string;
    constructor Create(ARegistry: TPcMetricRegistry; AIndex: Integer);
  end;

constructor TRecorderThread.Create(ARegistry: TPcMetricRegistry; AIndex: Integer);
begin
  FRegistry := ARegistry;
  FIndex := AIndex;
  inherited Create(False);
end;

procedure TRecorderThread.Execute;
var
  I: Integer;
  LKey: string;
begin
  try
    for I := 1 to OPS_PER_THREAD do
    begin
      // Two keys shared by every thread, so series creation races too.
      LKey := IntToStr(I mod 2);
      FRegistry.Counter('ops', '', '', ['key']).Labels([LKey]).Inc;
      FRegistry.UpDownCounter('active', '', '', []).Inc;
      FRegistry.Histogram('lat', 's', '', ['key'], [0.5]).Labels([LKey]).Observe(0.25);
      FRegistry.Counter('sum', '', '', []).Add(0.5);
      FRegistry.UpDownCounter('active', '', '', []).Dec;
    end;
  except
    on E: Exception do
      Error := E.ClassName + ': ' + E.Message;
  end;
end;

procedure TMetricsTests.Counter_AddsAndIgnoresNegativeAndNaN;
var
  LRegistry: TPcMetricRegistry;
  LCounter: TPcCounter;
begin
  LRegistry := TPcMetricRegistry.Create;
  try
    LCounter := LRegistry.Counter('c', '', '', []);
    LCounter.Inc;
    LCounter.Add(2.5);
    LCounter.Add(-1);
    LCounter.Add(NaN);
    TAssert.AssertEquals(3.5, LCounter.Labels([]).Value, 0);
  finally
    LRegistry.Free;
  end;
end;

procedure TMetricsTests.UpDownCounter_GoesBothWays;
var
  LRegistry: TPcMetricRegistry;
  LMetric: TPcUpDownCounter;
begin
  LRegistry := TPcMetricRegistry.Create;
  try
    LMetric := LRegistry.UpDownCounter('u', '', '', []);
    LMetric.Inc;
    LMetric.Inc;
    LMetric.Dec;
    LMetric.Add(-3);
    LMetric.Add(NaN);
    TAssert.AssertEquals(-2, LMetric.Labels([]).Value, 0);
  finally
    LRegistry.Free;
  end;
end;

procedure TMetricsTests.Gauge_SetsAndIgnoresNaN;
var
  LRegistry: TPcMetricRegistry;
  LGauge: TPcGauge;
begin
  LRegistry := TPcMetricRegistry.Create;
  try
    LGauge := LRegistry.Gauge('g', '', '', []);
    TAssert.AssertEquals('starts at 0', 0, LGauge.Labels([]).Value, 0);
    LGauge.SetValue(7.25);
    LGauge.SetValue(NaN);
    TAssert.AssertEquals(7.25, LGauge.Labels([]).Value, 0);
  finally
    LRegistry.Free;
  end;
end;

procedure TMetricsTests.Histogram_BoundsAreInclusive;
var
  LRegistry: TPcMetricRegistry;
  LHistogram: TPcHistogram;
  LPoints: TPcMetricPoints;
begin
  LRegistry := TPcMetricRegistry.Create;
  try
    LHistogram := LRegistry.Histogram('h', '', '', [], [1, 2, 5]);
    LHistogram.Observe(0.5);
    LHistogram.Observe(1);
    LHistogram.Observe(1.5);
    LHistogram.Observe(5);
    LHistogram.Observe(7);
    LHistogram.Observe(NaN);
    LPoints := LHistogram.Snapshot;
    TAssert.AssertEquals(1, Length(LPoints));
    TAssert.AssertEquals(4, Length(LPoints[0].BucketCounts));
    TAssert.AssertEquals('<= 1', 2, Integer(LPoints[0].BucketCounts[0]));
    TAssert.AssertEquals('<= 2', 1, Integer(LPoints[0].BucketCounts[1]));
    TAssert.AssertEquals('<= 5', 1, Integer(LPoints[0].BucketCounts[2]));
    TAssert.AssertEquals('> 5', 1, Integer(LPoints[0].BucketCounts[3]));
    TAssert.AssertEquals('count', 5, Integer(LPoints[0].Count));
    TAssert.AssertEquals('sum', 15, LPoints[0].Sum, 0);
    TAssert.AssertEquals(5, Integer(LHistogram.Labels([]).Count));
    TAssert.AssertEquals(15, LHistogram.Labels([]).Sum, 0);
  finally
    LRegistry.Free;
  end;
end;

procedure TMetricsTests.Histogram_WithoutBounds_HasOnlyTheInfBucket;
var
  LRegistry: TPcMetricRegistry;
  LHistogram: TPcHistogram;
begin
  LRegistry := TPcMetricRegistry.Create;
  try
    LHistogram := LRegistry.Histogram('h', '', '', [], []);
    LHistogram.Observe(-3);
    TAssert.AssertEquals('h_bucket{le="+Inf"} 1'#10'h_sum -3'#10'h_count 1'#10,
      Copy(PcPrometheusText(LRegistry), Length('# TYPE h histogram'#10) + 1, MaxInt));
  finally
    LRegistry.Free;
  end;
end;

procedure TMetricsTests.Labels_SameValues_SameSeries;
var
  LRegistry: TPcMetricRegistry;
  LCounter: TPcCounter;
begin
  LRegistry := TPcMetricRegistry.Create;
  try
    LCounter := LRegistry.Counter('c', '', '', ['a', 'b']);
    TAssert.AssertTrue(LCounter.Labels(['x', 'y']) = LCounter.Labels(['x', 'y']));
    TAssert.AssertFalse(LCounter.Labels(['x', 'y']) = LCounter.Labels(['y', 'x']));
    // A naive join would make these two the same key.
    TAssert.AssertFalse(LCounter.Labels(['x,', 'y']) = LCounter.Labels(['x', ',y']));
    TAssert.AssertEquals(4, Length(LCounter.Snapshot));
  finally
    LRegistry.Free;
  end;
end;

procedure TMetricsTests.Labels_WrongCount_Raises;
var
  LRegistry: TPcMetricRegistry;
  LCounter: TPcCounter;
begin
  LRegistry := TPcMetricRegistry.Create;
  try
    LCounter := LRegistry.Counter('c', '', '', ['a', 'b']);
    try
      LCounter.Labels(['x']);
      TAssert.Fail('one value for two labels');
    except
      on EPcMetrics do ;
    end;
    try
      LCounter.Inc;
      TAssert.Fail('Inc on a family with labels');
    except
      on EPcMetrics do ;
    end;
    TAssert.AssertEquals('no series created', 0, Length(LCounter.Snapshot));
  finally
    LRegistry.Free;
  end;
end;

procedure TMetricsTests.Labels_FamilyMethods_NeedNoLabels;
var
  LRegistry: TPcMetricRegistry;
  LHistogram: TPcHistogram;
begin
  LRegistry := TPcMetricRegistry.Create;
  try
    LHistogram := LRegistry.Histogram('h', '', '', [], [1]);
    TAssert.AssertEquals('the one series exists from the start', 1, Length(LHistogram.Snapshot));
    LHistogram.Observe(1);
    TAssert.AssertEquals(1, Integer(LHistogram.Labels([]).Count));
  finally
    LRegistry.Free;
  end;
end;

procedure TMetricsTests.Snapshot_InCreationOrder;
var
  LRegistry: TPcMetricRegistry;
  LGauge: TPcGauge;
  LPoints: TPcMetricPoints;
begin
  LRegistry := TPcMetricRegistry.Create;
  try
    LGauge := LRegistry.Gauge('g', '', '', ['k']);
    LGauge.Labels(['b']).SetValue(2);
    LGauge.Labels(['a']).SetValue(1);
    LPoints := LGauge.Snapshot;
    TAssert.AssertEquals(2, Length(LPoints));
    TAssert.AssertEquals('b', LPoints[0].LabelValues[0]);
    TAssert.AssertEquals(2, LPoints[0].Value, 0);
    TAssert.AssertEquals('a', LPoints[1].LabelValues[0]);
    TAssert.AssertEquals(1, LPoints[1].Value, 0);
  finally
    LRegistry.Free;
  end;
end;

procedure TMetricsTests.Registry_SameDefinition_ReturnsTheSameMetric;
var
  LRegistry: TPcMetricRegistry;
begin
  LRegistry := TPcMetricRegistry.Create;
  try
    TAssert.AssertTrue(LRegistry.Counter('c', 's', 'first', ['a']) =
      LRegistry.Counter('c', 's', 'second', ['a']));
    TAssert.AssertEquals('the first description stays', 'first',
      LRegistry.Counter('c', 's', '', ['a']).Description);
    TAssert.AssertTrue(LRegistry.Histogram('h', 's', '', [], [1, 2]) =
      LRegistry.Histogram('h', 's', '', [], [1, 2]));
    TAssert.AssertEquals(2, Length(LRegistry.Metrics));
  finally
    LRegistry.Free;
  end;
end;

procedure TMetricsTests.Registry_OtherDefinition_Raises;
var
  LRegistry: TPcMetricRegistry;

  procedure ExpectRaise(const AWhat: string; AStep: Integer);
  begin
    try
      case AStep of
        0: LRegistry.Gauge('c', 's', '', ['a']);
        1: LRegistry.Counter('c', 'ms', '', ['a']);
        2: LRegistry.Counter('c', 's', '', ['b']);
        3: LRegistry.Counter('c', 's', '', ['a', 'b']);
        4: LRegistry.Histogram('h', 's', '', [], [1, 3]);
        5: LRegistry.Histogram('h', 's', '', [], [1]);
      end;
      TAssert.Fail(AWhat);
    except
      on EPcMetrics do ;
    end;
  end;

begin
  LRegistry := TPcMetricRegistry.Create;
  try
    LRegistry.Counter('c', 's', '', ['a']);
    LRegistry.Histogram('h', 's', '', [], [1, 2]);
    ExpectRaise('another kind', 0);
    ExpectRaise('another unit', 1);
    ExpectRaise('another label', 2);
    ExpectRaise('more labels', 3);
    ExpectRaise('other bounds', 4);
    ExpectRaise('fewer bounds', 5);
    TAssert.AssertEquals(2, Length(LRegistry.Metrics));
  finally
    LRegistry.Free;
  end;
end;

procedure TMetricsTests.Registry_InvalidDefinitions_Raise;
var
  LRegistry: TPcMetricRegistry;

  procedure ExpectRaise(const AWhat: string; AStep: Integer);
  begin
    try
      case AStep of
        0: LRegistry.Counter('', '', '', []);
        1: LRegistry.Counter('1abc', '', '', []);
        2: LRegistry.Counter('a b', '', '', []);
        3: LRegistry.Counter(StringOfChar('a', 256), '', '', []);
        4: LRegistry.Counter('c', 'a b', '', []);
        5: LRegistry.Counter('c', '', '', ['']);
        6: LRegistry.Counter('c', '', '', ['1a']);
        7: LRegistry.Counter('c', '', '', ['__a']);
        8: LRegistry.Counter('c', '', '', ['a-b']);
        9: LRegistry.Counter('c', '', '', ['a', 'a']);
        10: LRegistry.Histogram('h', '', '', ['le'], []);
        11: LRegistry.Histogram('h', '', '', [], [2, 1]);
        12: LRegistry.Histogram('h', '', '', [], [1, 1]);
        13: LRegistry.Histogram('h', '', '', [], [1, Infinity]);
        14: LRegistry.Histogram('h', '', '', [], [NaN]);
      end;
      TAssert.Fail(AWhat);
    except
      on EPcMetrics do ;
    end;
  end;

begin
  LRegistry := TPcMetricRegistry.Create;
  try
    ExpectRaise('empty name', 0);
    ExpectRaise('name starting with a digit', 1);
    ExpectRaise('space in the name', 2);
    ExpectRaise('name of 256 characters', 3);
    ExpectRaise('space in the unit', 4);
    ExpectRaise('empty label', 5);
    ExpectRaise('label starting with a digit', 6);
    ExpectRaise('label starting with __', 7);
    ExpectRaise('dash in a label', 8);
    ExpectRaise('duplicate label', 9);
    ExpectRaise('histogram label le', 10);
    ExpectRaise('decreasing bounds', 11);
    ExpectRaise('repeated bound', 12);
    ExpectRaise('infinite bound', 13);
    ExpectRaise('NaN bound', 14);
    TAssert.AssertEquals('nothing registered', 0, Length(LRegistry.Metrics));
    LRegistry.Counter('a.b-c/d_e', '{request}/s', '', ['_x', 'y.z']);
    LRegistry.Counter(StringOfChar('a', 255), '', '', []);
  finally
    LRegistry.Free;
  end;
end;

procedure TMetricsTests.Registry_Metrics_InRegistrationOrder;
var
  LRegistry: TPcMetricRegistry;
  LMetrics: TPcMetricList;
begin
  LRegistry := TPcMetricRegistry.Create;
  try
    LRegistry.Gauge('z', '', '', []);
    LRegistry.Counter('a', '', '', []);
    LRegistry.Gauge('z', '', '', []);
    LMetrics := LRegistry.Metrics;
    TAssert.AssertEquals(2, Length(LMetrics));
    TAssert.AssertEquals('z', LMetrics[0].Name);
    TAssert.AssertEquals('a', LMetrics[1].Name);
    TAssert.AssertTrue(LMetrics[1].Kind = mkCounter);
  finally
    LRegistry.Free;
  end;
end;

procedure TMetricsTests.PrometheusName_FromOpenTelemetry;
var
  LRegistry: TPcMetricRegistry;
begin
  LRegistry := TPcMetricRegistry.Create;
  try
    TAssert.AssertEquals('http_server_request_duration_seconds',
      PcPrometheusName(LRegistry.Histogram('http.server.request.duration', 's', '', [], [])));
    TAssert.AssertEquals('http_server_active_requests',
      PcPrometheusName(LRegistry.UpDownCounter('http.server.active_requests', '{request}', '', [])));
    TAssert.AssertEquals('requests_total',
      PcPrometheusName(LRegistry.Counter('requests', '{request}', '', [])));
    TAssert.AssertEquals('no second _total', 'jobs_total',
      PcPrometheusName(LRegistry.Counter('jobs_total', '', '', [])));
    TAssert.AssertEquals('unit before _total', 'io_bytes_total',
      PcPrometheusName(LRegistry.Counter('io', 'By', '', [])));
    TAssert.AssertEquals('no second unit', 'wait_seconds',
      PcPrometheusName(LRegistry.Gauge('wait_seconds', 's', '', [])));
    TAssert.AssertEquals('1 on a gauge', 'cpu_utilization_ratio',
      PcPrometheusName(LRegistry.Gauge('cpu.utilization', '1', '', [])));
    TAssert.AssertEquals('1 on a counter', 'hits_total',
      PcPrometheusName(LRegistry.Counter('hits', '1', '', [])));
    TAssert.AssertEquals('per unit', 'throughput_bytes_per_second',
      PcPrometheusName(LRegistry.Gauge('throughput', 'By/s', '', [])));
    TAssert.AssertEquals('annotation per unit', 'rate_per_second',
      PcPrometheusName(LRegistry.Gauge('rate', '{request}/s', '', [])));
    TAssert.AssertEquals('unknown unit kept', 'distance_furlongs',
      PcPrometheusName(LRegistry.Gauge('distance', 'furlongs', '', [])));
    TAssert.AssertEquals('runs collapse', 'a_b_c',
      PcPrometheusName(LRegistry.Gauge('a..b/-c', '', '', [])));
    TAssert.AssertEquals('http_request_method', PcPrometheusLabelName('http.request.method'));
    TAssert.AssertEquals('_x', PcPrometheusLabelName('_x'));
  finally
    LRegistry.Free;
  end;
end;

procedure TMetricsTests.PrometheusFloat_Text;
var
  LSum: Double;
begin
  TAssert.AssertEquals('0', PcPrometheusFloat(0));
  TAssert.AssertEquals('3', PcPrometheusFloat(3));
  TAssert.AssertEquals('-42', PcPrometheusFloat(-42));
  TAssert.AssertEquals('9007199254740991', PcPrometheusFloat(9007199254740991.0));
  TAssert.AssertEquals('0.005', PcPrometheusFloat(0.005));
  TAssert.AssertEquals('0.1', PcPrometheusFloat(0.1));
  TAssert.AssertEquals('-2.5', PcPrometheusFloat(-2.5));
  TAssert.AssertEquals('7.5', PcPrometheusFloat(7.5));
  LSum := 0.1;
  LSum := LSum + 0.2;
  TAssert.AssertEquals('15 significant digits', '0.3', PcPrometheusFloat(LSum));
  TAssert.AssertEquals('NaN', PcPrometheusFloat(NaN));
  TAssert.AssertEquals('+Inf', PcPrometheusFloat(Infinity));
  TAssert.AssertEquals('-Inf', PcPrometheusFloat(NegInfinity));
  TAssert.AssertTrue('1e300 reads back',
    StrToFloat(StringReplace(PcPrometheusFloat(1e300), '.', FormatSettings.DecimalSeparator, []))
      = 1e300);
  TAssert.AssertTrue('1e-7 reads back',
    StrToFloat(StringReplace(PcPrometheusFloat(1e-7), '.', FormatSettings.DecimalSeparator, []))
      = 1e-7);
end;

procedure TMetricsTests.PrometheusText_ByteByByte;
const
  EXPECTED =
    '# HELP http_server_requests_total Requests.\nSecond line \\ back'#10 +
    '# TYPE http_server_requests_total counter'#10 +
    'http_server_requests_total{http_request_method="GET",http_response_status_code="200"} 3'#10 +
    'http_server_requests_total{http_request_method="PO\"ST\\x\n",http_response_status_code="500"} 1'#10 +
    '# TYPE queue_depth gauge'#10 +
    'queue_depth -2.5'#10 +
    '# HELP http_server_request_duration_seconds Duration.'#10 +
    '# TYPE http_server_request_duration_seconds histogram'#10 +
    'http_server_request_duration_seconds_bucket{http_route="/orders/:id",le="0.005"} 0'#10 +
    'http_server_request_duration_seconds_bucket{http_route="/orders/:id",le="0.25"} 1'#10 +
    'http_server_request_duration_seconds_bucket{http_route="/orders/:id",le="1"} 2'#10 +
    'http_server_request_duration_seconds_bucket{http_route="/orders/:id",le="+Inf"} 3'#10 +
    'http_server_request_duration_seconds_sum{http_route="/orders/:id"} 2.75'#10 +
    'http_server_request_duration_seconds_count{http_route="/orders/:id"} 3'#10;
var
  LRegistry: TPcMetricRegistry;
  LCounter: TPcCounter;
  LHistogram: TPcHistogramSeries;
begin
  LRegistry := TPcMetricRegistry.Create;
  try
    LCounter := LRegistry.Counter('http.server.requests', '{request}',
      'Requests.'#10'Second line \ back', ['http.request.method', 'http.response.status_code']);
    LCounter.Labels(['GET', '200']).Add(3);
    LCounter.Labels(['PO"ST\x'#10, '500']).Inc;
    LRegistry.Gauge('queue.depth', '', '', []).SetValue(-2.5);
    LHistogram := LRegistry.Histogram('http.server.request.duration', 's', 'Duration.',
      ['http.route'], [0.005, 0.25, 1]).Labels(['/orders/:id']);
    LHistogram.Observe(0.25);
    LHistogram.Observe(0.5);
    LHistogram.Observe(2);
    TAssert.AssertEquals(EXPECTED, PcPrometheusText(LRegistry));
  finally
    LRegistry.Free;
  end;
end;

procedure TMetricsTests.PrometheusText_EmptyRegistry;
var
  LRegistry: TPcMetricRegistry;
begin
  LRegistry := TPcMetricRegistry.Create;
  try
    TAssert.AssertEquals('', PcPrometheusText(LRegistry));
    LRegistry.Counter('c', '', '', ['k']);
    TAssert.AssertEquals('a family with labels and no series yet',
      '# TYPE c_total counter'#10, PcPrometheusText(LRegistry));
  finally
    LRegistry.Free;
  end;
end;

procedure TMetricsTests.Threads_RegisterAndRecord_ExactTotals;
var
  LRegistry: TPcMetricRegistry;
  LThreads: array[0..THREAD_COUNT - 1] of TRecorderThread;
  LOps: TPcCounter;
  LLat: TPcHistogram;
  I: Integer;
begin
  for I := 0 to THREAD_COUNT - 1 do
    LThreads[I] := nil;
  LRegistry := TPcMetricRegistry.Create;
  try
    try
      for I := 0 to THREAD_COUNT - 1 do
        LThreads[I] := TRecorderThread.Create(LRegistry, I);
      for I := 0 to THREAD_COUNT - 1 do
        LThreads[I].WaitFor;
      for I := 0 to THREAD_COUNT - 1 do
        TAssert.AssertEquals('thread error', '', LThreads[I].Error);
    finally
      for I := 0 to THREAD_COUNT - 1 do
        LThreads[I].Free;
    end;
    TAssert.AssertEquals('one registration each', 4, Length(LRegistry.Metrics));
    LOps := LRegistry.Counter('ops', '', '', ['key']);
    TAssert.AssertEquals('two series', 2, Length(LOps.Snapshot));
    TAssert.AssertEquals(THREAD_COUNT * OPS_PER_THREAD div 2, LOps.Labels(['0']).Value, 0);
    TAssert.AssertEquals(THREAD_COUNT * OPS_PER_THREAD div 2, LOps.Labels(['1']).Value, 0);
    TAssert.AssertEquals('back to 0', 0,
      LRegistry.UpDownCounter('active', '', '', []).Labels([]).Value, 0);
    LLat := LRegistry.Histogram('lat', 's', '', ['key'], [0.5]);
    TAssert.AssertEquals(THREAD_COUNT * OPS_PER_THREAD div 2, Integer(LLat.Labels(['0']).Count));
    TAssert.AssertEquals(THREAD_COUNT * OPS_PER_THREAD div 2 * 0.25, LLat.Labels(['0']).Sum, 0);
    TAssert.AssertEquals('Double CAS loses nothing', THREAD_COUNT * OPS_PER_THREAD * 0.5,
      LRegistry.Counter('sum', '', '', []).Labels([]).Value, 0);
  finally
    LRegistry.Free;
  end;
end;

procedure TMetricsTests.GlobalRegistry_Exists;
begin
  TAssert.AssertTrue(PcMetrics <> nil);
end;

initialization
  RegisterTest(TMetricsTests);

end.
