unit PascalCommon.TracingTests;

{$mode delphi}{$H+}

{ GENERATED FILE — produced by tools/gen_fpc_mirror.py from
  tests/Unit/PascalCommon.TracingTests.pas (DUnitX). Do not edit by hand: edit the DUnitX
  master and run the script again. }

{ Tests for PascalCommon.Tracing: spans and the current span, parent and
  child, sampling (flag and ratio), attributes and status, the batch
  processor (bounded queue, batch size, export failures, the export thread),
  tracing not started, a remote parent from a traceparent, the current span
  being per thread, spans finished on several threads at once, UTC Unix
  nanoseconds and the OTEL_* options.

  Most of them came from pascal-api-infra-faa's PascalApi.TracingTests with
  the unit (phase C of its observability design); the remote parent, Enabled,
  thread and export-thread tests are new here. The exporter is a fake that
  keeps what it gets. The processor runs without its thread (AAutoFlush =
  False) and FlushNow exports, except in the export-thread test, which waits
  on an event the fake sets, with a deadline, never on a Sleep.

  DUnitX master: the FPCUnit mirror in tests/Unit/fpc is generated by
  tools/gen_fpc_mirror.py. }

interface

uses
  fpcunit, testregistry,
  Classes,
  SysUtils,
  SyncObjs,
  DateUtils,
  PascalCommon.Tracing;

type
  TFakeSpanExporter = class(TInterfacedObject, IPcSpanExporter)
  public
    Spans: TPcSpanDataArray;
    Calls: Integer;
    Fail: Boolean;
    /// Set (when assigned) after each accepted batch.
    Received: TEvent;
    function ExportSpans(const ASpans: TPcSpanDataArray; out AError: string): Boolean;
  end;

  TTracingTests = class(TTestCase)
  private
    FFake: TFakeSpanExporter;
    FExporter: IPcSpanExporter;
    FErrors: TStringList;
    procedure StartWith(const AOptions: TPcTracingOptions; AAutoFlush: Boolean = False);
    procedure LogError(const ALine: string);
  protected
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure RootSpan_IsCurrent_ExportedOnFlush;
    procedure ChildSpan_SameTrace_ParentRestored;
    procedure StartSpanWith_KeepsIds;
    procedure NotSampled_NotExported_FlagZero;
    procedure Child_FollowsParentSampledFlag;
    procedure Ratio_ZeroOneAndHalf;
    procedure Attributes_TypesAndReplace;
    procedure Status_ErrorKeepsMessage_OkClearsIt;
    procedure Finish_Twice_ExportedOnce_LaterChangesIgnored;
    procedure Queue_Full_DropsOldest;
    procedure Batches_NoLargerThanMax;
    procedure ExportFailure_Reported_SpansDropped;
    procedure NotStarted_SpansWork_NothingExported;
    procedure Enabled_FollowsStartAndShutdown;
    procedure UnfinishedSpan_Freed_ClearsCurrent;
    procedure FromParent_Valid_ChildOfTheRemoteSpan;
    procedure FromParent_NotSampled_Followed;
    procedure FromParent_Invalid_NewTraceOrChildOfCurrent;
    procedure CurrentSpan_IsPerThread;
    procedure SpansFromSeveralThreads_AllExported;
    procedure ExportThread_ExportsWithoutFlushNow;
    procedure UnixNano_IsUtcMilliseconds;
    procedure Options_FromEnvironment;
  end;

implementation

const
  THREAD_COUNT = 4;
  SPANS_PER_THREAD = 200;

type
  TSpanThread = class(TThread)
  protected
    procedure Execute; override;
  public
    Error: string;
    CurrentAtStart: Boolean;
    constructor Create;
  end;

var
  GFakeEnv: TStringList;

function FakeEnvironment(const AName: string): string;
begin
  Result := GFakeEnv.Values[AName];
end;

// The current span's id, '' when none. A helper, so the temporary interface
// TPcTracing.Current returns is released here: in the test body it would keep
// the span alive until the end of the procedure.
function CurrentSpanId: string;
var
  LCurrent: IPcSpan;
begin
  LCurrent := TPcTracing.Current;
  if LCurrent = nil then
    Result := ''
  else
    Result := LCurrent.SpanId;
end;

constructor TSpanThread.Create;
begin
  inherited Create(False);
end;

procedure TSpanThread.Execute;
var
  I: Integer;
  P, C: IPcSpan;
begin
  try
    CurrentAtStart := TPcTracing.Current <> nil;
    for I := 1 to SPANS_PER_THREAD do
    begin
      P := TPcTracing.StartSpan('p');
      C := TPcTracing.StartSpan('c');
      if C.ParentSpanId <> P.SpanId then
        Error := 'child of the wrong parent';
      C.Finish;
      P.Finish;
      C := nil;
      P := nil;
    end;
  except
    on E: Exception do
      Error := E.ClassName + ': ' + E.Message;
  end;
end;

function TFakeSpanExporter.ExportSpans(const ASpans: TPcSpanDataArray; out AError: string): Boolean;
var
  I: Integer;
begin
  Inc(Calls);
  if Fail then
  begin
    AError := 'collector down';
    Exit(False);
  end;
  for I := 0 to High(ASpans) do
  begin
    SetLength(Spans, Length(Spans) + 1);
    Spans[High(Spans)] := ASpans[I];
  end;
  AError := '';
  Result := True;
  if Received <> nil then
    Received.SetEvent;
end;

{ TTracingTests }

procedure TTracingTests.Setup;
begin
  FErrors := TStringList.Create;
  StartWith(TPcTracingOptions.Default('svc', '1.2.3'));
end;

procedure TTracingTests.TearDown;
begin
  TPcTracing.Shutdown;
  FExporter := nil;
  FErrors.Free;
end;

procedure TTracingTests.StartWith(const AOptions: TPcTracingOptions; AAutoFlush: Boolean);
begin
  FFake := TFakeSpanExporter.Create;
  FExporter := FFake;
  TPcTracing.Start(AOptions, FExporter, LogError, AAutoFlush);
end;

procedure TTracingTests.LogError(const ALine: string);
begin
  FErrors.Add(ALine);
end;

procedure TTracingTests.RootSpan_IsCurrent_ExportedOnFlush;
var
  S: IPcSpan;
begin
  TAssert.AssertTrue('no current span at the start', TPcTracing.Current = nil);
  S := TPcTracing.StartSpan('work');
  TAssert.AssertTrue('the new span is the current one', TPcTracing.Current = S);
  TAssert.AssertEquals(32, Length(S.TraceId));
  TAssert.AssertEquals(16, Length(S.SpanId));
  TAssert.AssertEquals('', S.ParentSpanId);
  TAssert.AssertTrue(S.Sampled);
  S.Finish;
  TAssert.AssertTrue('finished: no current span', TPcTracing.Current = nil);
  TAssert.AssertEquals(0, Length(FFake.Spans));
  TAssert.AssertEquals(1, TPcTracing.PendingCount);
  TPcTracing.FlushNow;
  TAssert.AssertEquals(1, Length(FFake.Spans));
  TAssert.AssertEquals('work', FFake.Spans[0].Name);
  TAssert.AssertTrue(FFake.Spans[0].Kind = skInternal);
  TAssert.AssertEquals(S.SpanId, FFake.Spans[0].SpanId);
  TAssert.AssertTrue('end >= start', FFake.Spans[0].EndUnixNano >= FFake.Spans[0].StartUnixNano);
end;

procedure TTracingTests.ChildSpan_SameTrace_ParentRestored;
var
  P, C: IPcSpan;
begin
  P := TPcTracing.StartSpan('parent', skServer);
  C := TPcTracing.StartSpan('child');
  TAssert.AssertEquals(P.TraceId, C.TraceId);
  TAssert.AssertEquals(P.SpanId, C.ParentSpanId);
  TAssert.AssertTrue(C.SpanId <> P.SpanId);
  C.Finish;
  TAssert.AssertTrue('the parent is current again', TPcTracing.Current = P);
  P.Finish;
  TAssert.AssertTrue(TPcTracing.Current = nil);
  TPcTracing.FlushNow;
  TAssert.AssertEquals(2, Length(FFake.Spans));
  TAssert.AssertEquals('child', FFake.Spans[0].Name);
  TAssert.AssertTrue(FFake.Spans[1].Kind = skServer);
end;

procedure TTracingTests.StartSpanWith_KeepsIds;
var
  S: IPcSpan;
begin
  S := TPcTracing.StartSpanWith('4bf92f3577b34da6a3ce929d0e0e4736', 'b7ad6b7169203331',
    '00f067aa0ba902b7', 'vendor=1', True, 'GET /x', skServer);
  TAssert.AssertEquals('00-4bf92f3577b34da6a3ce929d0e0e4736-b7ad6b7169203331-01', S.TraceParent);
  TAssert.AssertEquals('vendor=1', S.TraceState);
  S.Finish;
  TPcTracing.FlushNow;
  TAssert.AssertEquals('00f067aa0ba902b7', FFake.Spans[0].ParentSpanId);
  TAssert.AssertEquals('vendor=1', FFake.Spans[0].TraceState);
end;

procedure TTracingTests.NotSampled_NotExported_FlagZero;
var
  S: IPcSpan;
begin
  S := TPcTracing.StartSpanWith('4bf92f3577b34da6a3ce929d0e0e4736', 'b7ad6b7169203331', '', '',
    False, 'x', skServer);
  TAssert.AssertEquals('00-4bf92f3577b34da6a3ce929d0e0e4736-b7ad6b7169203331-00', S.TraceParent);
  S.Finish;
  TPcTracing.FlushNow;
  TAssert.AssertEquals(0, Length(FFake.Spans));
end;

procedure TTracingTests.Child_FollowsParentSampledFlag;
var
  P, C: IPcSpan;
begin
  P := TPcTracing.StartSpanWith('4bf92f3577b34da6a3ce929d0e0e4736', 'b7ad6b7169203331', '', '',
    False, 'p', skServer);
  C := TPcTracing.StartSpan('c');
  TAssert.AssertFalse(C.Sampled);
  C.Finish;
  P.Finish;
  TPcTracing.FlushNow;
  TAssert.AssertEquals(0, Length(FFake.Spans));
end;

procedure TTracingTests.Ratio_ZeroOneAndHalf;
var
  O: TPcTracingOptions;
begin
  TAssert.AssertTrue(TPcTracing.ShouldSample('4bf92f3577b34da6ffffffffffffffff'));
  O := TPcTracingOptions.Default('svc', '1');
  O.SampleRatio := 0;
  StartWith(O);
  TAssert.AssertFalse(TPcTracing.ShouldSample('4bf92f3577b34da60000000000000000'));
  O.SampleRatio := 0.5;
  StartWith(O);
  // Below half of 2^64 by the last 16 hex digits: sampled.
  TAssert.AssertTrue(TPcTracing.ShouldSample('4bf92f3577b34da60000000000000000'));
  TAssert.AssertTrue(TPcTracing.ShouldSample('ffffffffffffffff7fffffffffffffff'));
  TAssert.AssertFalse(TPcTracing.ShouldSample('00000000000000008000000000000000'));
  TAssert.AssertFalse(TPcTracing.ShouldSample('4bf92f3577b34da6ffffffffffffffff'));
  // Not a trace id: never sampled.
  TAssert.AssertFalse(TPcTracing.ShouldSample('xyz'));
end;

procedure TTracingTests.Attributes_TypesAndReplace;
var
  S: IPcSpan;
  A: TPcSpanAttributes;
begin
  S := TPcTracing.StartSpan('a');
  S.SetAttribute('s', 'one');
  S.SetIntAttribute('i', 42);
  S.SetDoubleAttribute('d', 0.5);
  S.SetBoolAttribute('b', True);
  S.SetAttribute('s', 'two');
  S.Finish;
  TPcTracing.FlushNow;
  A := FFake.Spans[0].Attributes;
  TAssert.AssertEquals(4, Length(A));
  TAssert.AssertEquals('s', A[0].Key);
  TAssert.AssertEquals('two', A[0].StringValue);
  TAssert.AssertTrue(A[1].ValueType = satInt);
  TAssert.AssertEquals(Int64(42), A[1].IntValue);
  TAssert.AssertTrue(A[2].ValueType = satDouble);
  TAssert.AssertEquals(0.5, A[2].DoubleValue, 0);
  TAssert.AssertTrue(A[3].ValueType = satBool);
  TAssert.AssertTrue(A[3].BoolValue);
end;

procedure TTracingTests.Status_ErrorKeepsMessage_OkClearsIt;
var
  S: IPcSpan;
begin
  S := TPcTracing.StartSpan('a');
  S.SetStatus(ssError, 'boom');
  S.Finish;
  S := TPcTracing.StartSpan('b');
  S.SetStatus(ssError, 'boom');
  S.SetStatus(ssOk, 'ignored');
  S.Finish;
  TPcTracing.FlushNow;
  TAssert.AssertTrue(FFake.Spans[0].Status = ssError);
  TAssert.AssertEquals('boom', FFake.Spans[0].StatusMessage);
  TAssert.AssertTrue(FFake.Spans[1].Status = ssOk);
  TAssert.AssertEquals('', FFake.Spans[1].StatusMessage);
end;

procedure TTracingTests.Finish_Twice_ExportedOnce_LaterChangesIgnored;
var
  S: IPcSpan;
begin
  S := TPcTracing.StartSpan('a');
  S.Finish;
  S.SetAttribute('late', 'x');
  S.SetStatus(ssError, 'late');
  S.SetName('late');
  S.Finish;
  TPcTracing.FlushNow;
  TAssert.AssertEquals(1, Length(FFake.Spans));
  TAssert.AssertEquals(0, Length(FFake.Spans[0].Attributes));
  TAssert.AssertTrue(FFake.Spans[0].Status = ssUnset);
  TAssert.AssertEquals('a', FFake.Spans[0].Name);
end;

procedure TTracingTests.Queue_Full_DropsOldest;
var
  O: TPcTracingOptions;
  I: Integer;
begin
  O := TPcTracingOptions.Default('svc', '1');
  O.QueueCapacity := 2;
  StartWith(O);
  for I := 1 to 3 do
    TPcTracing.StartSpan('s' + IntToStr(I)).Finish;
  TAssert.AssertEquals(Int64(1), TPcTracing.DroppedCount);
  TPcTracing.FlushNow;
  TAssert.AssertEquals(2, Length(FFake.Spans));
  TAssert.AssertEquals('s2', FFake.Spans[0].Name);
  TAssert.AssertEquals('s3', FFake.Spans[1].Name);
end;

procedure TTracingTests.Batches_NoLargerThanMax;
var
  O: TPcTracingOptions;
  I: Integer;
begin
  O := TPcTracingOptions.Default('svc', '1');
  O.MaxBatchSize := 2;
  StartWith(O);
  for I := 1 to 5 do
    TPcTracing.StartSpan('s').Finish;
  TPcTracing.FlushNow;
  TAssert.AssertEquals(3, FFake.Calls);
  TAssert.AssertEquals(5, Length(FFake.Spans));
  TAssert.AssertEquals(0, TPcTracing.PendingCount);
end;

procedure TTracingTests.ExportFailure_Reported_SpansDropped;
begin
  FFake.Fail := True;
  TPcTracing.StartSpan('a').Finish;
  TPcTracing.FlushNow;
  TAssert.AssertEquals(1, FErrors.Count);
  TAssert.AssertEquals('span export failed (1 spans dropped): collector down', FErrors[0]);
  TAssert.AssertEquals(0, TPcTracing.PendingCount);
  // A later batch goes through again.
  FFake.Fail := False;
  TPcTracing.StartSpan('b').Finish;
  TPcTracing.FlushNow;
  TAssert.AssertEquals(1, Length(FFake.Spans));
end;

procedure TTracingTests.NotStarted_SpansWork_NothingExported;
var
  P, C: IPcSpan;
begin
  TPcTracing.Shutdown;
  TAssert.AssertFalse(TPcTracing.Enabled);
  P := TPcTracing.StartSpan('p');
  C := TPcTracing.StartSpan('c');
  TAssert.AssertEquals(P.TraceId, C.TraceId);
  C.SetAttribute('k', 'v');
  C.Finish;
  P.Finish;
  TPcTracing.FlushNow;
  TAssert.AssertEquals(0, Length(FFake.Spans));
  TAssert.AssertTrue(TPcTracing.Current = nil);
  TAssert.AssertEquals(0, TPcTracing.PendingCount);
  TAssert.AssertEquals(Int64(0), TPcTracing.DroppedCount);
end;

procedure TTracingTests.Enabled_FollowsStartAndShutdown;
begin
  TAssert.AssertTrue('started in Setup', TPcTracing.Enabled);
  TPcTracing.Shutdown;
  TAssert.AssertFalse(TPcTracing.Enabled);
  TPcTracing.Shutdown;
  TAssert.AssertFalse('a second Shutdown is harmless', TPcTracing.Enabled);
  StartWith(TPcTracingOptions.Default('svc', '1'));
  TAssert.AssertTrue(TPcTracing.Enabled);
  TAssert.AssertEquals('svc', TPcTracing.Options.ServiceName);
end;

procedure TTracingTests.UnfinishedSpan_Freed_ClearsCurrent;
var
  P, C: IPcSpan;
  LParentId: string;
begin
  P := TPcTracing.StartSpan('p');
  LParentId := P.SpanId;
  C := TPcTracing.StartSpan('c');
  C := nil; // never finished
  TAssert.AssertEquals('the parent is current again', LParentId, CurrentSpanId);
  P := nil;
  TAssert.AssertEquals('no current span', '', CurrentSpanId);
  TPcTracing.FlushNow;
  TAssert.AssertEquals(0, Length(FFake.Spans));
end;

procedure TTracingTests.FromParent_Valid_ChildOfTheRemoteSpan;
var
  S: IPcSpan;
begin
  S := TPcTracing.StartSpanFromParent('00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01',
    ' rojo=00f067aa0ba902b7 ', 'consume orders', skConsumer);
  TAssert.AssertEquals('4bf92f3577b34da6a3ce929d0e0e4736', S.TraceId);
  TAssert.AssertEquals('00f067aa0ba902b7', S.ParentSpanId);
  TAssert.AssertTrue('a new span id', S.SpanId <> '00f067aa0ba902b7');
  TAssert.AssertTrue(S.Sampled);
  TAssert.AssertEquals('tracestate trimmed', 'rojo=00f067aa0ba902b7', S.TraceState);
  TAssert.AssertTrue('the current span', TPcTracing.Current = S);
  S.Finish;
  TPcTracing.FlushNow;
  TAssert.AssertEquals(1, Length(FFake.Spans));
  TAssert.AssertTrue(FFake.Spans[0].Kind = skConsumer);
  TAssert.AssertEquals('00f067aa0ba902b7', FFake.Spans[0].ParentSpanId);
  S := TPcTracing.StartSpanFromParent('00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01',
    'k=' + StringOfChar('v', 600), 'x', skConsumer);
  TAssert.AssertEquals('a tracestate over 512 is dropped', '', S.TraceState);
  S.Finish;
end;

procedure TTracingTests.FromParent_NotSampled_Followed;
var
  S: IPcSpan;
begin
  S := TPcTracing.StartSpanFromParent('00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-00',
    '', 'x', skConsumer);
  TAssert.AssertFalse(S.Sampled);
  S.Finish;
  TPcTracing.FlushNow;
  TAssert.AssertEquals(0, Length(FFake.Spans));
end;

procedure TTracingTests.FromParent_Invalid_NewTraceOrChildOfCurrent;
var
  P, S: IPcSpan;
begin
  S := TPcTracing.StartSpanFromParent('garbage', 'rojo=1', 'x', skConsumer);
  TAssert.AssertEquals('a new trace', '', S.ParentSpanId);
  TAssert.AssertEquals(32, Length(S.TraceId));
  TAssert.AssertEquals('tracestate dropped with an invalid traceparent', '', S.TraceState);
  S.Finish;
  P := TPcTracing.StartSpan('p');
  S := TPcTracing.StartSpanFromParent('', '', 'x', skConsumer);
  TAssert.AssertEquals('a child of the current span', P.SpanId, S.ParentSpanId);
  TAssert.AssertEquals(P.TraceId, S.TraceId);
  S.Finish;
  P.Finish;
end;

procedure TTracingTests.CurrentSpan_IsPerThread;
var
  P: IPcSpan;
  LThread: TSpanThread;
begin
  P := TPcTracing.StartSpan('main');
  LThread := TSpanThread.Create;
  try
    LThread.WaitFor;
    TAssert.AssertEquals('', LThread.Error);
    TAssert.AssertFalse('another thread starts with no current span', LThread.CurrentAtStart);
  finally
    LThread.Free;
  end;
  TAssert.AssertTrue('this thread''s current span is untouched', TPcTracing.Current = P);
  P.Finish;
end;

procedure TTracingTests.SpansFromSeveralThreads_AllExported;
var
  LThreads: array[0..THREAD_COUNT - 1] of TSpanThread;
  O: TPcTracingOptions;
  I: Integer;
begin
  O := TPcTracingOptions.Default('svc', '1');
  O.QueueCapacity := THREAD_COUNT * SPANS_PER_THREAD * 2;
  StartWith(O);
  for I := 0 to THREAD_COUNT - 1 do
    LThreads[I] := nil;
  try
    for I := 0 to THREAD_COUNT - 1 do
      LThreads[I] := TSpanThread.Create;
    for I := 0 to THREAD_COUNT - 1 do
      LThreads[I].WaitFor;
    for I := 0 to THREAD_COUNT - 1 do
      TAssert.AssertEquals('thread error', '', LThreads[I].Error);
  finally
    for I := 0 to THREAD_COUNT - 1 do
      LThreads[I].Free;
  end;
  TPcTracing.FlushNow;
  TAssert.AssertEquals(THREAD_COUNT * SPANS_PER_THREAD * 2, Length(FFake.Spans));
  TAssert.AssertEquals(Int64(0), TPcTracing.DroppedCount);
end;

procedure TTracingTests.ExportThread_ExportsWithoutFlushNow;
var
  O: TPcTracingOptions;
  LReceived: TEvent;
begin
  LReceived := TEvent.Create(nil, True, False, '');
  try
    O := TPcTracingOptions.Default('svc', '1');
    O.FlushIntervalMs := 10;
    StartWith(O, True);
    FFake.Received := LReceived;
    TPcTracing.StartSpan('background').Finish;
    TAssert.AssertTrue('exported by the processor thread within 5 s',
      LReceived.WaitFor(5000) = wrSignaled);
    TPcTracing.Shutdown;
    TAssert.AssertEquals(1, Length(FFake.Spans));
    TAssert.AssertEquals('background', FFake.Spans[0].Name);
  finally
    TPcTracing.Shutdown;
    FFake.Received := nil;
    LReceived.Free;
  end;
end;

procedure TTracingTests.UnixNano_IsUtcMilliseconds;
var
  T: TDateTime;
begin
  T := EncodeDate(2026, 1, 2) + EncodeTime(3, 4, 5, 678);
  // DateTimeToUnix(T, False) is UTC seconds of a local time (measured on both
  // compilers in pascal-api-infra-faa, for JWT).
  TAssert.AssertEquals((DateTimeToUnix(T, False) * 1000 + 678) * 1000000, PcUnixNanoOfLocal(T));
end;

procedure TTracingTests.Options_FromEnvironment;
var
  O: TPcTracingOptions;
begin
  GFakeEnv := TStringList.Create;
  try
    O := TPcTracingOptions.FromEnvironment('default-name', '1.0', FakeEnvironment);
    TAssert.AssertEquals('default-name', O.ServiceName);
    TAssert.AssertEquals(1, O.SampleRatio, 0);
    TAssert.AssertEquals(5000, O.FlushIntervalMs);
    TAssert.AssertEquals(2048, O.QueueCapacity);
    TAssert.AssertEquals(512, O.MaxBatchSize);
    GFakeEnv.Values['OTEL_SERVICE_NAME'] := 'from-env';
    GFakeEnv.Values['OTEL_TRACES_SAMPLER_ARG'] := '0.25';
    GFakeEnv.Values['OTEL_BSP_SCHEDULE_DELAY'] := '200';
    GFakeEnv.Values['OTEL_BSP_MAX_QUEUE_SIZE'] := '10';
    GFakeEnv.Values['OTEL_BSP_MAX_EXPORT_BATCH_SIZE'] := '0';
    GFakeEnv.Values['OTEL_RESOURCE_ATTRIBUTES'] := 'deployment.environment=test';
    O := TPcTracingOptions.FromEnvironment('default-name', '1.0', FakeEnvironment);
    TAssert.AssertEquals('from-env', O.ServiceName);
    TAssert.AssertEquals('1.0', O.ServiceVersion);
    TAssert.AssertEquals(0.25, O.SampleRatio, 0);
    TAssert.AssertEquals(200, O.FlushIntervalMs);
    TAssert.AssertEquals(10, O.QueueCapacity);
    TAssert.AssertEquals('0 keeps the default', 512, O.MaxBatchSize);
    TAssert.AssertEquals('deployment.environment=test', O.ResourceAttributes);
    GFakeEnv.Values['OTEL_TRACES_SAMPLER_ARG'] := '2';
    GFakeEnv.Values['OTEL_BSP_SCHEDULE_DELAY'] := 'soon';
    O := TPcTracingOptions.FromEnvironment('n', 'v', FakeEnvironment);
    TAssert.AssertEquals('out of range keeps 1', 1, O.SampleRatio, 0);
    TAssert.AssertEquals('not a number keeps the default', 5000, O.FlushIntervalMs);
  finally
    FreeAndNil(GFakeEnv);
  end;
  // The process environment overload: only checked where the variable isn't
  // set (a developer machine or CI with OTEL_SERVICE_NAME would differ).
  if GetEnvironmentVariable('OTEL_SERVICE_NAME') = '' then
    TAssert.AssertEquals('proc', TPcTracingOptions.FromEnvironment('proc', '1').ServiceName);
end;

initialization
  RegisterTest(TTracingTests);

end.
