unit PascalCommon.ThreadPoolTests;

{$mode delphi}{$H+}

{ GENERATED FILE — produced by tools/gen_fpc_mirror.py from
  tests/Unit/PascalCommon.ThreadPoolTests.pas (DUnitX). Do not edit by hand: edit the DUnitX
  master and run the script again. }

{ Tests for PascalCommon.ThreadPool: the monitor (timeout and PulseAll), the
  pool (runs every item, survives an exception, Destroy runs what is still
  queued, QueueDepth) and the process-wide PcPool.

  Ported from the monitor/pool part of Pipes.ThreadingTests
  (pascal-named-pipes-faa), translated and rewritten in the TAssert dialect.
  QueueDepth and the finalization check are new.

  Waits are deterministic: events or counters polled up to a deadline, never
  a bare Sleep followed by a hope. The only Sleeps are inside work items, to
  keep the queue busy, and in the timeout test, which checks a lower bound.

  This unit's finalization also checks the claim in PascalCommon.ThreadPool's
  header: a unit that uses PascalCommon.ThreadPool is finalized before it, so
  PcPool still runs work at that point. If it didn't, the finalization below
  would crash or time out after the test results, and it sets ExitCode to 1
  and prints "FINALIZATION CHECK FAILED", which tools/test_fpc.sh and
  tools/test_fpc_docker.sh look for. It runs on every suite run, on both compilers.

  DUnitX master: the FPCUnit mirror in tests/Unit/fpc is generated by
  tools/gen_fpc_mirror.py. }

interface

uses
  fpcunit, testregistry,
  SysUtils,
  Classes,
  SyncObjs,
  PascalCommon.Threading,
  PascalCommon.ThreadPool;

type
  TThreadPoolTests = class(TTestCase)
  published
    procedure Monitor_WaitWithTimeout_ReturnsAfterTheTimeout;
    procedure Monitor_PulseAll_WakesTheWaiterBeforeTheTimeout;
    procedure Pool_RunsEveryItem;
    procedure Pool_ExceptionInAnItemDoesNotKillTheWorker;
    procedure Pool_DestroyRunsTheQueuedItems;
    procedure Pool_QueueDepth_CountsOnlyWaitingItems;
    procedure PcPool_IsCreatedAndAlwaysTheSameInstance;
    procedure PcPool_RunsWork;
  end;

implementation

type
  { Increments a shared counter, after an optional delay (to fill the queue
    in the shutdown test). }
  TCounterWork = class(TPcWorkItem)
  private
    FCounter: PInteger;
    FDelayMs: Integer;
  public
    constructor Create(ACounter: PInteger; ADelayMs: Integer = 0);
    procedure Execute; override;
  end;

  TRaiseWork = class(TPcWorkItem)
  public
    procedure Execute; override;
  end;

  { Signals AStarted, then blocks until ARelease is set (deadline 10 s). }
  TBlockingWork = class(TPcWorkItem)
  private
    FStarted: TEvent;
    FRelease: TEvent;
  public
    constructor Create(AStarted, ARelease: TEvent);
    procedure Execute; override;
  end;

  TSignalWork = class(TPcWorkItem)
  private
    FDone: TEvent;
  public
    constructor Create(ADone: TEvent);
    procedure Execute; override;
  end;

  { Enters the monitor, says it is about to wait, and waits for a PulseAll. }
  TMonitorWaiter = class(TThread)
  private
    FMon: TPcMonitor;
    FInWait: PInteger;
    FAwake: PInteger;
  protected
    procedure Execute; override;
  public
    constructor Create(AMon: TPcMonitor; AInWait, AAwake: PInteger);
  end;

constructor TCounterWork.Create(ACounter: PInteger; ADelayMs: Integer);
begin
  inherited Create;
  FCounter := ACounter;
  FDelayMs := ADelayMs;
end;

procedure TCounterWork.Execute;
begin
  if FDelayMs > 0 then
    Sleep(FDelayMs);
  PcAtomicInc(FCounter^);
end;

procedure TRaiseWork.Execute;
begin
  raise Exception.Create('exception raised on purpose by the test');
end;

constructor TBlockingWork.Create(AStarted, ARelease: TEvent);
begin
  inherited Create;
  FStarted := AStarted;
  FRelease := ARelease;
end;

procedure TBlockingWork.Execute;
begin
  FStarted.SetEvent;
  FRelease.WaitFor(10000);
end;

constructor TSignalWork.Create(ADone: TEvent);
begin
  inherited Create;
  FDone := ADone;
end;

procedure TSignalWork.Execute;
begin
  FDone.SetEvent;
end;

constructor TMonitorWaiter.Create(AMon: TPcMonitor; AInWait, AAwake: PInteger);
begin
  FMon := AMon;
  FInWait := AInWait;
  FAwake := AAwake;
  FreeOnTerminate := False;
  inherited Create(False);
end;

procedure TMonitorWaiter.Execute;
begin
  FMon.Enter;
  PcAtomicSet(FInWait^, 1);
  FMon.Wait(10000); // woken by the test's PulseAll; 10 s is the escape hatch
  FMon.Leave;
  PcAtomicSet(FAwake^, 1);
end;

// Waits for ACounter to reach AExpected (polling); False past the deadline.
function WaitCounter(var ACounter: Integer; AExpected: Integer;
  ATimeoutMs: Cardinal): Boolean;
var
  LDeadline: UInt64;
begin
  LDeadline := PcTickMs + ATimeoutMs;
  while (PcAtomicGet(ACounter) <> AExpected) and (PcTickMs < LDeadline) do
    Sleep(5);
  Result := PcAtomicGet(ACounter) = AExpected;
end;

{ TThreadPoolTests }

procedure TThreadPoolTests.Monitor_WaitWithTimeout_ReturnsAfterTheTimeout;
var
  LMon: TPcMonitor;
  T0: UInt64;
begin
  LMon := TPcMonitor.Create;
  try
    LMon.Enter;
    T0 := PcTickMs;
    LMon.Wait(200);
    LMon.Leave;
    TAssert.AssertTrue('Wait returned before the timeout', PcTickMs - T0 >= 150);
  finally
    LMon.Free;
  end;
end;

procedure TThreadPoolTests.Monitor_PulseAll_WakesTheWaiterBeforeTheTimeout;
var
  LMon: TPcMonitor;
  LWaiter: TMonitorWaiter;
  LInWait, LAwake: Integer;
  T0: UInt64;
begin
  LInWait := 0;
  LAwake := 0;
  LMon := TPcMonitor.Create;
  try
    LWaiter := TMonitorWaiter.Create(LMon, @LInWait, @LAwake);
    try
      TAssert.AssertTrue('the waiter never reached Wait', WaitCounter(LInWait, 1, 2000));
      // This Enter only returns after the waiter has taken the generation and
      // released the lock (inside Wait), so the PulseAll wakes exactly it.
      LMon.Enter;
      T0 := PcTickMs;
      LMon.PulseAll;
      LMon.Leave;
      TAssert.AssertTrue('PulseAll did not wake the waiter', WaitCounter(LAwake, 1, 3000));
      TAssert.AssertTrue('the waiter only woke up on its timeout', PcTickMs - T0 < 5000);
    finally
      LWaiter.WaitFor;
      LWaiter.Free;
    end;
  finally
    LMon.Free;
  end;
end;

procedure TThreadPoolTests.Pool_RunsEveryItem;
var
  LPool: TPcThreadPool;
  LCounter, I: Integer;
begin
  LCounter := 0;
  LPool := TPcThreadPool.Create(4);
  try
    for I := 1 to 50 do
      LPool.Queue(TCounterWork.Create(@LCounter));
    TAssert.AssertTrue('the pool did not run the 50 items', WaitCounter(LCounter, 50, 5000));
  finally
    LPool.Free;
  end;
end;

procedure TThreadPoolTests.Pool_ExceptionInAnItemDoesNotKillTheWorker;
var
  LPool: TPcThreadPool;
  LCounter: Integer;
begin
  LCounter := 0;
  // One worker: the next item proves the SAME worker survived the exception.
  LPool := TPcThreadPool.Create(1);
  try
    LPool.Queue(TRaiseWork.Create);
    LPool.Queue(TCounterWork.Create(@LCounter));
    TAssert.AssertTrue('the worker died after the exception', WaitCounter(LCounter, 1, 5000));
  finally
    LPool.Free;
  end;
end;

procedure TThreadPoolTests.Pool_DestroyRunsTheQueuedItems;
var
  LPool: TPcThreadPool;
  LCounter, I: Integer;
begin
  LCounter := 0;
  LPool := TPcThreadPool.Create(2);
  for I := 1 to 20 do
    LPool.Queue(TCounterWork.Create(@LCounter, 30)); // 30 ms each: the queue builds up
  // Destroy lets the workers drain the queue, then joins them. If it hung,
  // the suite would hang (and the CI job time out).
  LPool.Free;
  TAssert.AssertEquals('Destroy must run every queued item', 20, PcAtomicGet(LCounter));
end;

procedure TThreadPoolTests.Pool_QueueDepth_CountsOnlyWaitingItems;
var
  LPool: TPcThreadPool;
  LStarted, LRelease: TEvent;
  LCounter, I: Integer;
begin
  LCounter := 0;
  LStarted := TEvent.Create(nil, True, False, '');
  LRelease := TEvent.Create(nil, True, False, '');
  LPool := TPcThreadPool.Create(1);
  try
    TAssert.AssertEquals(0, LPool.QueueDepth);
    LPool.Queue(TBlockingWork.Create(LStarted, LRelease));
    TAssert.AssertTrue('the blocking item never started',
      LStarted.WaitFor(5000) = wrSignaled);
    // The only worker is busy: these three wait in the queue.
    for I := 1 to 3 do
      LPool.Queue(TCounterWork.Create(@LCounter));
    TAssert.AssertEquals(3, LPool.QueueDepth);
    LRelease.SetEvent;
    TAssert.AssertTrue('the queued items did not run', WaitCounter(LCounter, 3, 5000));
    TAssert.AssertEquals(0, LPool.QueueDepth);
  finally
    LRelease.SetEvent;
    LPool.Free;
    LRelease.Free;
    LStarted.Free;
  end;
end;

procedure TThreadPoolTests.PcPool_IsCreatedAndAlwaysTheSameInstance;
begin
  TAssert.AssertTrue('PcPool must exist from initialization on', PcPool <> nil);
  TAssert.AssertTrue(PcPool = PcPool);
end;

procedure TThreadPoolTests.PcPool_RunsWork;
var
  LDone: TEvent;
begin
  LDone := TEvent.Create(nil, True, False, '');
  try
    PcPool.Queue(TSignalWork.Create(LDone));
    TAssert.AssertTrue('PcPool did not run the item', LDone.WaitFor(5000) = wrSignaled);
  finally
    LDone.Free;
  end;
end;

// See the unit header: PcPool must still run work during the finalization of
// a unit that uses PascalCommon.ThreadPool.
procedure CheckPcPoolAliveInFinalization;
var
  LDone: TEvent;
begin
  if PcPool = nil then
  begin
    WriteLn(ErrOutput, 'FINALIZATION CHECK FAILED (PascalCommon.ThreadPoolTests): PcPool already freed');
    ExitCode := 1;
    Exit;
  end;
  LDone := TEvent.Create(nil, True, False, '');
  try
    PcPool.Queue(TSignalWork.Create(LDone));
    if LDone.WaitFor(5000) <> wrSignaled then
    begin
      WriteLn(ErrOutput, 'FINALIZATION CHECK FAILED (PascalCommon.ThreadPoolTests): PcPool did not run the item');
      ExitCode := 1;
    end;
  finally
    LDone.Free;
  end;
end;

initialization
  RegisterTest(TThreadPoolTests);

finalization
  CheckPcPoolAliveInFinalization;

end.
