unit PascalCommon.Utf8Tests;

{$mode delphi}{$H+}

{ GENERATED FILE — produced by tools/gen_fpc_mirror.py from
  tests/Unit/PascalCommon.Utf8Tests.pas (DUnitX). Do not edit by hand: edit the DUnitX
  master and run the script again. }

{ Tests for PascalCommon.Utf8: ASCII and non-ASCII text, the BOM, empty
  input, and on FPC the refusal outside a UTF-8 code page (the test switches
  the code page to 1252 and back, as pascal-db-faa's SqlSources tests did for
  the function this replaces there).

  DUnitX master: the FPCUnit mirror in tests/Unit/fpc is generated by
  tools/gen_fpc_mirror.py. }

interface

uses
  fpcunit, testregistry,
  SysUtils,
  PascalCommon.Utf8;

type
  TUtf8Tests = class(TTestCase)
  published
    procedure Ascii;
    procedure NonAscii;
    procedure Bom_IsDropped;
    procedure Empty_And_BomOnly;
    procedure NonAscii_OutsideUtf8CodePage_IsRefusedOnFpc;
  end;

implementation

function Bytes(const AValues: array of Byte): TBytes;
var
  I: Integer;
begin
  Result := nil;
  SetLength(Result, Length(AValues));
  for I := 0 to High(AValues) do
    Result[I] := AValues[I];
end;

// 'São →' in UTF-8.
function NonAsciiBytes: TBytes;
begin
  Result := Bytes([$53, $C3, $A3, $6F, $20, $E2, $86, $92]);
end;

procedure TUtf8Tests.Ascii;
var
  LText: string;
begin
  TAssert.AssertTrue(PcTryUtf8BytesToString(Bytes([$6F, $6B]), LText));
  TAssert.AssertEquals('ok', LText);
end;

procedure TUtf8Tests.NonAscii;
var
  LText: string;
begin
  TAssert.AssertTrue(PcTryUtf8BytesToString(NonAsciiBytes, LText));
  TAssert.AssertEquals('São →', LText);
end;

procedure TUtf8Tests.Bom_IsDropped;
var
  LText: string;
begin
  TAssert.AssertTrue(PcTryUtf8BytesToString(Bytes([$EF, $BB, $BF, $C3, $A3]), LText));
  TAssert.AssertEquals('ã', LText);
end;

procedure TUtf8Tests.Empty_And_BomOnly;
var
  LText: string;
begin
  LText := 'x';
  TAssert.AssertTrue(PcTryUtf8BytesToString(nil, LText));
  TAssert.AssertEquals('', LText);
  TAssert.AssertTrue(PcTryUtf8BytesToString(Bytes([$EF, $BB, $BF]), LText));
  TAssert.AssertEquals('', LText);
end;

procedure TUtf8Tests.NonAscii_OutsideUtf8CodePage_IsRefusedOnFpc;
var
  LText: string;
  {$IFDEF FPC}
  LOldCodePage: TSystemCodePage;
  LResult, LAsciiResult: Boolean;
  {$ENDIF}
begin
  {$IFDEF FPC}
  LOldCodePage := DefaultSystemCodePage;
  SetMultiByteConversionCodePage(1252);
  try
    LResult := PcTryUtf8BytesToString(NonAsciiBytes, LText);
    LAsciiResult := PcTryUtf8BytesToString(Bytes([$6F, $6B]), LText);
  finally
    SetMultiByteConversionCodePage(LOldCodePage);
  end;
  TAssert.AssertFalse('non-ASCII outside UTF-8 is refused', LResult);
  TAssert.AssertTrue('ASCII is fine in any code page', LAsciiResult);
  TAssert.AssertEquals('ok', LText);
  {$ELSE}
  // Delphi: string is UTF-16, there is no code page to guard.
  TAssert.AssertTrue(PcTryUtf8BytesToString(NonAsciiBytes, LText));
  TAssert.AssertEquals('São →', LText);
  {$ENDIF}
end;

initialization
  RegisterTest(TUtf8Tests);

end.
