unit PascalCommon.TraceContextTests;

{$mode delphi}{$H+}

{ GENERATED FILE — produced by tools/gen_fpc_mirror.py from
  tests/Unit/PascalCommon.TraceContextTests.pas (DUnitX). Do not edit by hand: edit the DUnitX
  master and run the script again. }

{ Tests for PascalCommon.TraceContext: id generation (shape, never zero, no
  repeats, from several threads at once), id validation, and traceparent /
  tracestate against the W3C Trace Context Level 1 text: the specification's
  example header, version 00's exact length, version ff, a higher version's
  forward compatibility, uppercase hex, all-zero ids, wrong lengths and
  separators, surrounding spaces and tabs, and the 512-character tracestate
  limit.

  The threaded test waits on TThread.WaitFor, not on a Sleep: on POSIX the
  threads share one /dev/urandom descriptor, which is what it exercises.

  DUnitX master: the FPCUnit mirror in tests/Unit/fpc is generated by
  tools/gen_fpc_mirror.py. }

interface

uses
  fpcunit, testregistry,
  Classes,
  SysUtils,
  PascalCommon.TraceContext;

type
  TTraceContextTests = class(TTestCase)
  published
    procedure NewTraceId_IsValid;
    procedure NewSpanId_IsValid;
    procedure NewIds_DoNotRepeat;
    procedure NewIds_FromSeveralThreads_DoNotRepeat;
    procedure IsValidTraceId_Rules;
    procedure IsValidSpanId_Rules;
    procedure Parse_SpecExample_Sampled;
    procedure Parse_SpecExample_NotSampled;
    procedure Parse_UnknownFlagBits_AreKept;
    procedure Parse_SurroundingSpacesAndTabs_AreIgnored;
    procedure Parse_Version00_WithExtraField_IsInvalid;
    procedure Parse_VersionFF_IsInvalid;
    procedure Parse_HigherVersion_IsForwardCompatible;
    procedure Parse_HigherVersion_56thCharNotDash_IsInvalid;
    procedure Parse_UppercaseHex_IsInvalid;
    procedure Parse_ZeroIds_AreInvalid;
    procedure Parse_WrongLengthsAndSeparators_AreInvalid;
    procedure Parse_Invalid_ClearsTheRecord;
    procedure Format_WritesVersion00;
    procedure Format_ThenParse_RoundTrips;
    procedure TraceState_ForwardedOnlyWithValidParent;
    procedure TraceState_LengthLimit;
  end;

implementation

const
  SPEC_TRACE_ID = '4bf92f3577b34da6a3ce929d0e0e4736';
  SPEC_PARENT_ID = '00f067aa0ba902b7';
  SPEC_SAMPLED = '00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01';
  SPEC_NOT_SAMPLED = '00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-00';
  THREAD_COUNT = 4;
  IDS_PER_THREAD = 500;

type
  TIdThread = class(TThread)
  protected
    procedure Execute; override;
  public
    Ids: TStringList;
    Error: string;
    constructor Create;
    destructor Destroy; override;
  end;

constructor TIdThread.Create;
begin
  Ids := TStringList.Create;
  inherited Create(False);
end;

destructor TIdThread.Destroy;
begin
  Ids.Free;
  inherited;
end;

procedure TIdThread.Execute;
var
  I: Integer;
begin
  try
    for I := 1 to IDS_PER_THREAD do
      Ids.Add(PcNewTraceId);
  except
    on E: Exception do
      Error := E.ClassName + ': ' + E.Message;
  end;
end;

function IsValidParent(const AHeader: string): Boolean;
var
  LParent: TPcTraceParent;
begin
  Result := PcTryParseTraceParent(AHeader, LParent);
end;

procedure TTraceContextTests.NewTraceId_IsValid;
var
  LId: string;
begin
  LId := PcNewTraceId;
  TAssert.AssertEquals(32, Length(LId));
  TAssert.AssertTrue(LId, PcIsValidTraceId(LId));
end;

procedure TTraceContextTests.NewSpanId_IsValid;
var
  LId: string;
begin
  LId := PcNewSpanId;
  TAssert.AssertEquals(16, Length(LId));
  TAssert.AssertTrue(LId, PcIsValidSpanId(LId));
end;

procedure TTraceContextTests.NewIds_DoNotRepeat;
var
  LTraceIds, LSpanIds: TStringList;
  I: Integer;
begin
  LTraceIds := TStringList.Create;
  LSpanIds := TStringList.Create;
  try
    LTraceIds.Sorted := True;
    LTraceIds.Duplicates := dupIgnore;
    LSpanIds.Sorted := True;
    LSpanIds.Duplicates := dupIgnore;
    for I := 1 to 2000 do
    begin
      LTraceIds.Add(PcNewTraceId);
      LSpanIds.Add(PcNewSpanId);
    end;
    TAssert.AssertEquals('trace ids', 2000, LTraceIds.Count);
    TAssert.AssertEquals('span ids', 2000, LSpanIds.Count);
  finally
    LSpanIds.Free;
    LTraceIds.Free;
  end;
end;

procedure TTraceContextTests.NewIds_FromSeveralThreads_DoNotRepeat;
var
  LThreads: array[0..THREAD_COUNT - 1] of TIdThread;
  LAll: TStringList;
  I, J: Integer;
begin
  for I := 0 to THREAD_COUNT - 1 do
    LThreads[I] := nil;
  LAll := TStringList.Create;
  try
    for I := 0 to THREAD_COUNT - 1 do
      LThreads[I] := TIdThread.Create;
    for I := 0 to THREAD_COUNT - 1 do
      LThreads[I].WaitFor;
    LAll.Sorted := True;
    LAll.Duplicates := dupIgnore;
    for I := 0 to THREAD_COUNT - 1 do
    begin
      TAssert.AssertEquals('thread error', '', LThreads[I].Error);
      for J := 0 to LThreads[I].Ids.Count - 1 do
      begin
        if not PcIsValidTraceId(LThreads[I].Ids[J]) then
          TAssert.Fail('invalid id ' + LThreads[I].Ids[J]);
        LAll.Add(LThreads[I].Ids[J]);
      end;
    end;
    TAssert.AssertEquals(THREAD_COUNT * IDS_PER_THREAD, LAll.Count);
  finally
    for I := 0 to THREAD_COUNT - 1 do
      LThreads[I].Free;
    LAll.Free;
  end;
end;

procedure TTraceContextTests.IsValidTraceId_Rules;
begin
  TAssert.AssertTrue(PcIsValidTraceId(SPEC_TRACE_ID));
  TAssert.AssertTrue('one non-zero digit', PcIsValidTraceId('00000000000000000000000000000001'));
  TAssert.AssertFalse('all zeros', PcIsValidTraceId('00000000000000000000000000000000'));
  TAssert.AssertFalse('uppercase', PcIsValidTraceId('4BF92F3577B34DA6A3CE929D0E0E4736'));
  TAssert.AssertFalse('non-hex', PcIsValidTraceId('4bf92f3577b34da6a3ce929d0e0e473g'));
  TAssert.AssertFalse('31 digits', PcIsValidTraceId('4bf92f3577b34da6a3ce929d0e0e473'));
  TAssert.AssertFalse('33 digits', PcIsValidTraceId('4bf92f3577b34da6a3ce929d0e0e47360'));
  TAssert.AssertFalse('empty', PcIsValidTraceId(''));
  TAssert.AssertFalse('a span id', PcIsValidTraceId(SPEC_PARENT_ID));
end;

procedure TTraceContextTests.IsValidSpanId_Rules;
begin
  TAssert.AssertTrue(PcIsValidSpanId(SPEC_PARENT_ID));
  TAssert.AssertFalse('all zeros', PcIsValidSpanId('0000000000000000'));
  TAssert.AssertFalse('uppercase', PcIsValidSpanId('00F067AA0BA902B7'));
  TAssert.AssertFalse('15 digits', PcIsValidSpanId('00f067aa0ba902b'));
  TAssert.AssertFalse('17 digits', PcIsValidSpanId('00f067aa0ba902b70'));
  TAssert.AssertFalse('a trace id', PcIsValidSpanId(SPEC_TRACE_ID));
end;

procedure TTraceContextTests.Parse_SpecExample_Sampled;
var
  LParent: TPcTraceParent;
begin
  TAssert.AssertTrue(PcTryParseTraceParent(SPEC_SAMPLED, LParent));
  TAssert.AssertEquals(0, LParent.Version);
  TAssert.AssertEquals(SPEC_TRACE_ID, LParent.TraceId);
  TAssert.AssertEquals(SPEC_PARENT_ID, LParent.ParentId);
  TAssert.AssertEquals(1, LParent.Flags);
  TAssert.AssertTrue(LParent.Sampled);
end;

procedure TTraceContextTests.Parse_SpecExample_NotSampled;
var
  LParent: TPcTraceParent;
begin
  TAssert.AssertTrue(PcTryParseTraceParent(SPEC_NOT_SAMPLED, LParent));
  TAssert.AssertEquals(0, LParent.Flags);
  TAssert.AssertFalse(LParent.Sampled);
end;

procedure TTraceContextTests.Parse_UnknownFlagBits_AreKept;
var
  LParent: TPcTraceParent;
begin
  TAssert.AssertTrue(PcTryParseTraceParent('00-' + SPEC_TRACE_ID + '-' + SPEC_PARENT_ID + '-09', LParent));
  TAssert.AssertEquals(9, LParent.Flags);
  TAssert.AssertTrue(LParent.Sampled);
  TAssert.AssertTrue(PcTryParseTraceParent('00-' + SPEC_TRACE_ID + '-' + SPEC_PARENT_ID + '-fe', LParent));
  TAssert.AssertEquals($FE, LParent.Flags);
  TAssert.AssertFalse(LParent.Sampled);
end;

procedure TTraceContextTests.Parse_SurroundingSpacesAndTabs_AreIgnored;
var
  LParent: TPcTraceParent;
begin
  TAssert.AssertTrue(PcTryParseTraceParent(' '#9 + SPEC_SAMPLED + #9' ', LParent));
  TAssert.AssertEquals(SPEC_TRACE_ID, LParent.TraceId);
  TAssert.AssertFalse('a space inside', IsValidParent('00-' + SPEC_TRACE_ID + ' -' + SPEC_PARENT_ID + '-01'));
end;

procedure TTraceContextTests.Parse_Version00_WithExtraField_IsInvalid;
begin
  TAssert.AssertFalse(IsValidParent(SPEC_SAMPLED + '-what-the-future-will-be-like'));
  TAssert.AssertFalse(IsValidParent(SPEC_SAMPLED + '-'));
end;

procedure TTraceContextTests.Parse_VersionFF_IsInvalid;
begin
  TAssert.AssertFalse(IsValidParent('ff-' + SPEC_TRACE_ID + '-' + SPEC_PARENT_ID + '-01'));
end;

procedure TTraceContextTests.Parse_HigherVersion_IsForwardCompatible;
var
  LParent: TPcTraceParent;
begin
  TAssert.AssertTrue('exactly 55', PcTryParseTraceParent('cc-' + SPEC_TRACE_ID + '-' + SPEC_PARENT_ID + '-01', LParent));
  TAssert.AssertEquals($CC, LParent.Version);
  TAssert.AssertTrue('with a future field', PcTryParseTraceParent(
    'cc-' + SPEC_TRACE_ID + '-' + SPEC_PARENT_ID + '-01-what-the-future-will-be-like', LParent));
  TAssert.AssertEquals(SPEC_TRACE_ID, LParent.TraceId);
  TAssert.AssertEquals(SPEC_PARENT_ID, LParent.ParentId);
  TAssert.AssertTrue(LParent.Sampled);
  TAssert.AssertEquals('written back as 00', SPEC_SAMPLED,
    PcFormatTraceParent(LParent.TraceId, LParent.ParentId, LParent.Sampled));
end;

procedure TTraceContextTests.Parse_HigherVersion_56thCharNotDash_IsInvalid;
begin
  TAssert.AssertFalse(IsValidParent('cc-' + SPEC_TRACE_ID + '-' + SPEC_PARENT_ID + '-01.what-the-future-will-be-like'));
  TAssert.AssertFalse('shorter than 55', IsValidParent('cc-' + SPEC_TRACE_ID + '-' + SPEC_PARENT_ID + '-1'));
end;

procedure TTraceContextTests.Parse_UppercaseHex_IsInvalid;
begin
  TAssert.AssertFalse('version', IsValidParent('0A-' + SPEC_TRACE_ID + '-' + SPEC_PARENT_ID + '-01'));
  TAssert.AssertFalse('trace id', IsValidParent('00-4BF92F3577B34DA6A3CE929D0E0E4736-' + SPEC_PARENT_ID + '-01'));
  TAssert.AssertFalse('parent id', IsValidParent('00-' + SPEC_TRACE_ID + '-00F067AA0BA902B7-01'));
  TAssert.AssertFalse('flags', IsValidParent('00-' + SPEC_TRACE_ID + '-' + SPEC_PARENT_ID + '-0A'));
end;

procedure TTraceContextTests.Parse_ZeroIds_AreInvalid;
begin
  TAssert.AssertFalse('trace id', IsValidParent('00-00000000000000000000000000000000-' + SPEC_PARENT_ID + '-01'));
  TAssert.AssertFalse('parent id', IsValidParent('00-' + SPEC_TRACE_ID + '-0000000000000000-01'));
end;

procedure TTraceContextTests.Parse_WrongLengthsAndSeparators_AreInvalid;
begin
  TAssert.AssertFalse('empty', IsValidParent(''));
  TAssert.AssertFalse('only spaces', IsValidParent('   '));
  TAssert.AssertFalse('short trace id', IsValidParent('00-4bf92f3577b34da6a3ce929d0e0e473-' + SPEC_PARENT_ID + '-01'));
  TAssert.AssertFalse('long trace id', IsValidParent('00-4bf92f3577b34da6a3ce929d0e0e47360-' + SPEC_PARENT_ID + '-01'));
  TAssert.AssertFalse('short parent id', IsValidParent('00-' + SPEC_TRACE_ID + '-00f067aa0ba902b-01'));
  TAssert.AssertFalse('long parent id', IsValidParent('00-' + SPEC_TRACE_ID + '-00f067aa0ba902b70-01'));
  TAssert.AssertFalse('one-digit flags', IsValidParent('00-' + SPEC_TRACE_ID + '-' + SPEC_PARENT_ID + '-1'));
  TAssert.AssertFalse('three-digit flags', IsValidParent('00-' + SPEC_TRACE_ID + '-' + SPEC_PARENT_ID + '-001'));
  TAssert.AssertFalse('one-digit version', IsValidParent('0-' + SPEC_TRACE_ID + '-' + SPEC_PARENT_ID + '-01'));
  TAssert.AssertFalse('underscores', IsValidParent('00_' + SPEC_TRACE_ID + '_' + SPEC_PARENT_ID + '_01'));
  TAssert.AssertFalse('non-hex version', IsValidParent('0g-' + SPEC_TRACE_ID + '-' + SPEC_PARENT_ID + '-01'));
end;

procedure TTraceContextTests.Parse_Invalid_ClearsTheRecord;
var
  LParent: TPcTraceParent;
begin
  TAssert.AssertTrue(PcTryParseTraceParent(SPEC_SAMPLED, LParent));
  TAssert.AssertFalse(PcTryParseTraceParent('garbage', LParent));
  TAssert.AssertEquals('', LParent.TraceId);
  TAssert.AssertEquals('', LParent.ParentId);
  TAssert.AssertEquals(0, LParent.Flags);
  TAssert.AssertEquals(0, LParent.Version);
end;

procedure TTraceContextTests.Format_WritesVersion00;
begin
  TAssert.AssertEquals(SPEC_SAMPLED, PcFormatTraceParent(SPEC_TRACE_ID, SPEC_PARENT_ID, True));
  TAssert.AssertEquals(SPEC_NOT_SAMPLED, PcFormatTraceParent(SPEC_TRACE_ID, SPEC_PARENT_ID, False));
end;

procedure TTraceContextTests.Format_ThenParse_RoundTrips;
var
  LTraceId, LSpanId, LHeader: string;
  LParent: TPcTraceParent;
begin
  LTraceId := PcNewTraceId;
  LSpanId := PcNewSpanId;
  LHeader := PcFormatTraceParent(LTraceId, LSpanId, True);
  TAssert.AssertEquals(PC_TRACEPARENT_LENGTH, Length(LHeader));
  TAssert.AssertTrue(LHeader, PcTryParseTraceParent(LHeader, LParent));
  TAssert.AssertEquals(LTraceId, LParent.TraceId);
  TAssert.AssertEquals(LSpanId, LParent.ParentId);
  TAssert.AssertTrue(LParent.Sampled);
end;

procedure TTraceContextTests.TraceState_ForwardedOnlyWithValidParent;
begin
  TAssert.AssertEquals('rojo=00f067aa0ba902b7,congo=t61rcWkgMzE',
    PcResolveTraceState(True, 'rojo=00f067aa0ba902b7,congo=t61rcWkgMzE'));
  TAssert.AssertEquals('surrounding OWS trimmed', 'congo=t61rcWkgMzE',
    PcResolveTraceState(True, #9' congo=t61rcWkgMzE '));
  TAssert.AssertEquals('dropped without a valid traceparent', '',
    PcResolveTraceState(False, 'rojo=00f067aa0ba902b7'));
  TAssert.AssertEquals('', PcResolveTraceState(True, ''));
end;

procedure TTraceContextTests.TraceState_LengthLimit;
var
  L512: string;
begin
  L512 := 'k=' + StringOfChar('v', PC_TRACESTATE_MAX_LENGTH - 2);
  TAssert.AssertEquals(512, Length(L512));
  TAssert.AssertEquals('512 kept', L512, PcResolveTraceState(True, L512));
  TAssert.AssertEquals('513 dropped', '', PcResolveTraceState(True, L512 + 'v'));
end;

initialization
  RegisterTest(TTraceContextTests);

end.
