unit PascalCommon.ThreadingTests;

{ Tests for PascalCommon.Threading: the 32-bit atomics, both overloads of the
  64-bit atomics (including values above High(Int64) and wrap-around) and the
  two monotonic clocks.

  The concurrent Add64 tests are what catch a broken atomic: a sequential test
  passes with a plain "Inc". They are deterministic: the threads run a fixed
  number of additions and are joined with WaitFor before the total is
  checked. The clock tests only assert lower bounds after a Sleep (a loaded
  machine sleeps longer, never shorter, within the timer's granularity) and
  compare the two clocks over the same interval.

  UInt64 results are compared with AssertTrue(A = B): FPCUnit's TAssert has
  no UInt64 overload, and passing one to the Int64 overload would hide
  exactly the values above High(Int64) these tests care about.

  Ported from the atomics part of Pipes.ThreadingTests (pascal-named-pipes-
  faa), translated and rewritten in the TAssert dialect. DUnitX master: the
  FPCUnit mirror in tests/Unit/fpc is generated by tools/gen_fpc_mirror.py. }

interface

uses
  DUnitX.TestFramework,
  PascalCommon.DUnitXCompat,
  SysUtils,
  Classes,
  PascalCommon.Threading;

type
  [TestFixture]
  TThreadingTests = class
  public
    [Test] procedure Atomic_IncDec_ReturnNewValue;
    [Test] procedure Atomic_SetReturnsOld_CompareExchangeSwapsOnlyIfEqual;
    [Test] procedure Atomic64_Signed_IncAddReadWrite;
    [Test] procedure Atomic64_Signed_CompareExchangeSwapsOnlyIfEqual;
    [Test] procedure Atomic64_Unsigned_RoundTripAboveHighInt64;
    [Test] procedure Atomic64_Unsigned_IncAdd;
    [Test] procedure Atomic64_Unsigned_CompareExchangeSwapsOnlyIfEqual;
    [Test] procedure Atomic64_Add_WrapsAround;
    [Test] procedure Atomic64_Signed_ConcurrentAddLosesNothing;
    [Test] procedure Atomic64_Unsigned_ConcurrentAddLosesNothing;
    [Test] procedure TickMs_AdvancesAndNeverGoesBack;
    [Test] procedure TickUs_AdvancesAndNeverGoesBack;
    [Test] procedure TickUs_AgreesWithTickMs;
  end;

implementation

const
  NUM_THREADS = 8;
  TIMES_PER_THREAD = 20000;

type
  { Adds 1 to a shared counter TIMES_PER_THREAD times, through the Int64 or
    the UInt64 overload of PcAtomicAdd64. }
  TAdderThread = class(TThread)
  private
    FSigned: PInt64;
    FUnsigned: PUInt64;
  protected
    procedure Execute; override;
  public
    constructor Create(ASigned: PInt64; AUnsigned: PUInt64);
  end;

constructor TAdderThread.Create(ASigned: PInt64; AUnsigned: PUInt64);
begin
  FSigned := ASigned;
  FUnsigned := AUnsigned;
  FreeOnTerminate := False;
  inherited Create(False);
end;

procedure TAdderThread.Execute;
var
  I: Integer;
begin
  for I := 1 to TIMES_PER_THREAD do
    if FSigned <> nil then
      PcAtomicAdd64(FSigned^, 1)
    else
      PcAtomicAdd64(FUnsigned^, 1);
end;

// Starts NUM_THREADS adders on the same counter and joins them all.
procedure RunAdders(ASigned: PInt64; AUnsigned: PUInt64);
var
  LThreads: array[0..NUM_THREADS - 1] of TAdderThread;
  I: Integer;
begin
  for I := 0 to NUM_THREADS - 1 do
    LThreads[I] := TAdderThread.Create(ASigned, AUnsigned);
  for I := 0 to NUM_THREADS - 1 do
  begin
    LThreads[I].WaitFor;
    LThreads[I].Free;
  end;
end;

{ TThreadingTests }

procedure TThreadingTests.Atomic_IncDec_ReturnNewValue;
var
  V: Integer;
begin
  V := 0;
  TAssert.AssertEquals(1, PcAtomicInc(V));
  TAssert.AssertEquals(2, PcAtomicInc(V));
  TAssert.AssertEquals(1, PcAtomicDec(V));
  TAssert.AssertEquals(1, PcAtomicGet(V));
end;

procedure TThreadingTests.Atomic_SetReturnsOld_CompareExchangeSwapsOnlyIfEqual;
var
  V: Integer;
begin
  V := 5;
  TAssert.AssertEquals(5, PcAtomicSet(V, 9));
  TAssert.AssertEquals(9, PcAtomicGet(V));
  TAssert.AssertEquals(9, PcAtomicCompareExchange(V, 20, 9));    // comparand matches: swaps
  TAssert.AssertEquals(20, PcAtomicGet(V));
  TAssert.AssertEquals(20, PcAtomicCompareExchange(V, 30, 99));  // doesn't match: keeps
  TAssert.AssertEquals(20, PcAtomicGet(V));
end;

procedure TThreadingTests.Atomic64_Signed_IncAddReadWrite;
var
  V: Int64;
begin
  V := 0;
  TAssert.AssertEquals(Int64(1), PcAtomicInc64(V));
  TAssert.AssertEquals(Int64(11), PcAtomicAdd64(V, 10));
  TAssert.AssertEquals(Int64(-4), PcAtomicAdd64(V, -15));
  TAssert.AssertEquals(Int64(-4), PcAtomicRead64(V));
  PcAtomicWrite64(V, Int64($0123456789ABCDEF));
  TAssert.AssertEquals('64-bit round trip corrupted the value',
    Int64($0123456789ABCDEF), PcAtomicRead64(V));
end;

procedure TThreadingTests.Atomic64_Signed_CompareExchangeSwapsOnlyIfEqual;
var
  V: Int64;
begin
  V := -100;
  TAssert.AssertEquals(Int64(-100), PcAtomicCompareExchange64(V, 200, -100));
  TAssert.AssertEquals(Int64(200), V);
  TAssert.AssertEquals(Int64(200), PcAtomicCompareExchange64(V, 300, 999));
  TAssert.AssertEquals('comparand did not match: value must not change',
    Int64(200), V);
end;

procedure TThreadingTests.Atomic64_Unsigned_RoundTripAboveHighInt64;
var
  V, LBig: UInt64;
begin
  LBig := UInt64(High(Int64));
  LBig := LBig + 12345;  // above High(Int64): the sign bit is set
  V := 0;
  PcAtomicWrite64(V, LBig);
  TAssert.AssertTrue('64-bit round trip corrupted the value', PcAtomicRead64(V) = LBig);
  TAssert.AssertTrue(V = LBig);
end;

procedure TThreadingTests.Atomic64_Unsigned_IncAdd;
var
  V, LBig: UInt64;
begin
  V := 0;
  TAssert.AssertTrue(PcAtomicInc64(V) = 1);
  TAssert.AssertTrue(PcAtomicAdd64(V, 10) = 11);
  LBig := UInt64(High(Int64));
  V := LBig;
  TAssert.AssertTrue('adding across High(Int64) must stay unsigned',
    PcAtomicAdd64(V, 2) = LBig + 2);
  TAssert.AssertTrue(PcAtomicInc64(V) = LBig + 3);
  TAssert.AssertTrue(V = LBig + 3);
end;

procedure TThreadingTests.Atomic64_Unsigned_CompareExchangeSwapsOnlyIfEqual;
var
  V, LBig: UInt64;
begin
  LBig := UInt64(High(Int64));
  LBig := LBig + 7;
  V := LBig;
  TAssert.AssertTrue('returns the OLD value',
    PcAtomicCompareExchange64(V, 200, LBig) = LBig);
  TAssert.AssertTrue(V = 200);
  TAssert.AssertTrue(PcAtomicCompareExchange64(V, 300, LBig) = 200);
  TAssert.AssertTrue('comparand did not match: value must not change', V = 200);
end;

procedure TThreadingTests.Atomic64_Add_WrapsAround;
var
  S: Int64;
  U: UInt64;
begin
  // The unit turns overflow checks off: the shared value wraps in hardware,
  // and the returned value must agree with it instead of raising.
  S := High(Int64);
  TAssert.AssertEquals(Low(Int64), PcAtomicInc64(S));
  TAssert.AssertEquals(Low(Int64), S);
  U := High(UInt64);
  TAssert.AssertTrue(PcAtomicInc64(U) = 0);
  TAssert.AssertTrue(U = 0);
end;

procedure TThreadingTests.Atomic64_Signed_ConcurrentAddLosesNothing;
var
  LCounter: Int64;
begin
  LCounter := 0;
  RunAdders(@LCounter, nil);
  TAssert.AssertEquals('atomic add lost increments under concurrency',
    Int64(NUM_THREADS) * TIMES_PER_THREAD, LCounter);
end;

procedure TThreadingTests.Atomic64_Unsigned_ConcurrentAddLosesNothing;
var
  LCounter, LStart: UInt64;
begin
  // Start above High(Int64), so the additions run with the sign bit set.
  LStart := UInt64(High(Int64));
  LCounter := LStart;
  RunAdders(nil, @LCounter);
  TAssert.AssertTrue('atomic add lost increments under concurrency',
    LCounter = LStart + UInt64(NUM_THREADS) * TIMES_PER_THREAD);
end;

procedure TThreadingTests.TickMs_AdvancesAndNeverGoesBack;
var
  T1, T2: UInt64;
begin
  T1 := PcTickMs;
  Sleep(50);
  T2 := PcTickMs;
  TAssert.AssertTrue('monotonic tick went back', T2 >= T1);
  // 50 ms of sleep minus one tick of GetTickCount64's granularity (~16 ms).
  TAssert.AssertTrue(Format('advanced only %d ms', [Int64(T2 - T1)]), T2 - T1 >= 30);
end;

procedure TThreadingTests.TickUs_AdvancesAndNeverGoesBack;
var
  T1, T2: Int64;
  I: Integer;
begin
  T1 := PcTickUs;
  for I := 1 to 1000 do
  begin
    T2 := PcTickUs;
    TAssert.AssertTrue('monotonic tick went back', T2 >= T1);
    T1 := T2;
  end;
  T1 := PcTickUs;
  Sleep(50);
  T2 := PcTickUs;
  TAssert.AssertTrue(Format('advanced only %d us', [T2 - T1]), T2 - T1 >= 30000);
end;

procedure TThreadingTests.TickUs_AgreesWithTickMs;
var
  LUs0, LUs1: Int64;
  LMs0, LMs1: UInt64;
  LDiffMs: Int64;
begin
  // Both clocks over the same interval; the tolerance covers GetTickCount64's
  // 16 ms steps at each end.
  LMs0 := PcTickMs;
  LUs0 := PcTickUs;
  Sleep(200);
  LUs1 := PcTickUs;
  LMs1 := PcTickMs;
  LDiffMs := (LUs1 - LUs0) div 1000 - Int64(LMs1 - LMs0);
  TAssert.AssertTrue(Format('TickUs and TickMs disagree by %d ms', [LDiffMs]),
    Abs(LDiffMs) <= 40);
end;

initialization
  TDUnitX.RegisterTestFixture(TThreadingTests);

end.
