unit PascalCommon.SystemContextTests;

{ Tests for PascalCommon.SystemContext: replacing and restoring the clock,
  ticker and sleep, the nil-means-default rule of the setters, and
  TTicker.ElapsedMs never wrapping around.

  In pascal-db-faa these providers were only exercised indirectly, through
  the pool's tests. Here they get their own fixture, since every consumer
  relies on them. TearDown restores the three defaults, so a failing test
  doesn't leave a fake behind for the next one.

  DUnitX master: the FPCUnit mirror in tests/Unit/fpc is generated by
  tools/gen_fpc_mirror.py. }

interface

uses
  DUnitX.TestFramework,
  PascalCommon.DUnitXCompat,
  SysUtils,
  PascalCommon.SystemContext,
  PascalCommon.Threading;

type
  [TestFixture]
  TSystemContextTests = class
  public
    [TearDown] procedure TearDown;
    [Test] procedure Clock_SetClock_ReplacesAndResetRestores;
    [Test] procedure Clock_SetClockNil_RestoresDefault;
    [Test] procedure Ticker_SetTicker_ReplacesAndResetRestores;
    [Test] procedure Ticker_ElapsedMs_NeverWrapsAround;
    [Test] procedure Sleep_SetSleep_ReplacesAndResetRestores;
  end;

implementation

type
  TFixedClock = class(TInterfacedObject, IClock)
  private
    FNow: TDateTime;
  public
    constructor Create(ANow: TDateTime);
    function Now: TDateTime;
    function Date: TDateTime;
  end;

  TManualTicker = class(TInterfacedObject, ITicker)
  public
    Ms: UInt64;
    function NowMs: UInt64;
  end;

  TRecordingSleep = class(TInterfacedObject, ISleep)
  public
    TotalMs: Cardinal;
    procedure Sleep(milliseconds: Cardinal);
  end;

constructor TFixedClock.Create(ANow: TDateTime);
begin
  inherited Create;
  FNow := ANow;
end;

function TFixedClock.Now: TDateTime;
begin
  Result := FNow;
end;

function TFixedClock.Date: TDateTime;
begin
  Result := Trunc(FNow);
end;

function TManualTicker.NowMs: UInt64;
begin
  Result := Ms;
end;

procedure TRecordingSleep.Sleep(milliseconds: Cardinal);
begin
  Inc(TotalMs, milliseconds);
end;

{ TSystemContextTests }

procedure TSystemContextTests.TearDown;
begin
  TClock.Reset;
  TTicker.Reset;
  TSleep.Reset;
end;

procedure TSystemContextTests.Clock_SetClock_ReplacesAndResetRestores;
var
  LFixed: TDateTime;
begin
  LFixed := EncodeDate(2001, 2, 3) + EncodeTime(4, 5, 6, 0);
  TClock.SetClock(TFixedClock.Create(LFixed));
  TAssert.AssertEquals(LFixed, TClock.Now, 0);
  TAssert.AssertEquals(EncodeDate(2001, 2, 3), TClock.Date, 0);
  TClock.Reset;
  TAssert.AssertTrue('Reset must bring back the system clock',
    Abs(TClock.Now - SysUtils.Now) < 1 / 24);
end;

procedure TSystemContextTests.Clock_SetClockNil_RestoresDefault;
begin
  TClock.SetClock(TFixedClock.Create(EncodeDate(2001, 2, 3)));
  TClock.SetClock(nil);
  TAssert.AssertTrue('SetClock(nil) must bring back the system clock',
    Abs(TClock.Now - SysUtils.Now) < 1 / 24);
end;

procedure TSystemContextTests.Ticker_SetTicker_ReplacesAndResetRestores;
var
  LTicker: TManualTicker;
  LTickerRef: ITicker;
  LBefore, LAfter: UInt64;
begin
  LTicker := TManualTicker.Create;
  LTickerRef := LTicker;
  LTicker.Ms := 1000;
  TTicker.SetTicker(LTickerRef);
  TAssert.AssertTrue(TTicker.NowMs = 1000);
  LTicker.Ms := 1500;
  TAssert.AssertTrue(TTicker.ElapsedMs(1000) = 500);
  TTicker.SetTicker(nil);
  LBefore := PcTickMs;
  LAfter := TTicker.NowMs;
  TAssert.AssertTrue('SetTicker(nil) must bring back PcTickMs',
    (LAfter >= LBefore) and (LAfter - LBefore < 1000));
end;

procedure TSystemContextTests.Ticker_ElapsedMs_NeverWrapsAround;
var
  LTicker: TManualTicker;
  LTickerRef: ITicker;
begin
  LTicker := TManualTicker.Create;
  LTickerRef := LTicker;
  LTicker.Ms := 100;
  TTicker.SetTicker(LTickerRef);
  TAssert.AssertTrue('a "since" ahead of now must give 0, not a huge number',
    TTicker.ElapsedMs(200) = 0);
  TAssert.AssertTrue(TTicker.ElapsedMs(100) = 0);
  TAssert.AssertTrue(TTicker.ElapsedMs(40) = 60);
end;

procedure TSystemContextTests.Sleep_SetSleep_ReplacesAndResetRestores;
var
  LSleep: TRecordingSleep;
  LSleepRef: ISleep;
  T0: UInt64;
begin
  LSleep := TRecordingSleep.Create;
  LSleepRef := LSleep;
  TSleep.SetSleep(LSleepRef);
  T0 := PcTickMs;
  TSleep.Sleep(60000);
  TSleep.Sleep(5);
  TAssert.AssertTrue('the fake sleep must not block', PcTickMs - T0 < 5000);
  TAssert.AssertEquals(Int64(60005), Int64(LSleep.TotalMs));
  TSleep.Reset;
  T0 := PcTickMs;
  TSleep.Sleep(50);
  TAssert.AssertTrue('Reset must bring back the real Sleep', PcTickMs - T0 >= 30);
end;

initialization
  TDUnitX.RegisterTestFixture(TSystemContextTests);

end.
