unit PascalCommon.SafeLogTests;

{ Tests for PascalCommon.SafeLog: what SafeWriteln writes, that it writes
  nothing (and doesn't format) without a console, and that concurrent writers
  don't corrupt each other's lines.

  The output is captured with a text-file driver of the test's own: Output is
  reassigned to a device whose InOutFunc appends the buffer to a memory stream.
  Its FlushFunc does nothing, which is how the RTL treats a file or a pipe:
  Writeln doesn't flush, the buffer goes out when it fills. It can't be nil:
  FPC skips a nil FlushFunc (its own stdout has one when redirected), but
  Delphi calls it unchecked, an access violation at address 0 (measured on
  Delphi 12, Win32 and Win64). That is the case where FPC
  needs SafeWriteln's Flush (unit header of PascalCommon.SafeLog, gotcha 8), so
  the concurrent test fails on FPC without it, on Windows as well as Linux.
  Output is a threadvar on FPC: there each writer thread redirects its own
  Output; on Delphi it is one global, redirected once by the test. The main
  thread's Output record is saved byte for byte and copied back afterwards: its
  BufPtr points into the record itself, so the copy stays valid.

  IsConsole is set explicitly in every test and restored: the FPC GUI runner on
  Windows runs without a console.

  The concurrent test checks what can be checked from inside the process: every
  line arrives whole, none is lost, and each writer's lines arrive in the order
  it wrote them. It doesn't check that two libraries share the lock; that holds
  by construction, since there is one unit. The threads start together on an
  event, wait for it with a deadline and are joined with WaitFor.

  DUnitX master: the FPCUnit mirror in tests/Unit/fpc is generated by
  tools/gen_fpc_mirror.py. }

interface

uses
  DUnitX.TestFramework,
  PascalCommon.DUnitXCompat,
  SysUtils,
  Classes,
  SyncObjs,
  PascalCommon.SafeLog;

type
  [TestFixture]
  TSafeLogTests = class
  public
    [Test] procedure WritesTheLine;
    [Test] procedure FormatOverload_FormatsTheLine;
    [Test] procedure NoConsole_WritesNothing;
    [Test] procedure NoConsole_FormatOverloadDoesntFormat;
    [Test] procedure ConcurrentWriters_EveryLineWholeAndInOrder;
  end;

implementation

const
  NUM_WRITERS = 8;
  LINES_PER_WRITER = 2000;
  // longer than either RTL's text buffer (Delphi 128, FPC 256 bytes), so a
  // buffer often fills in the middle of a line
  LINE_WIDTH = 300;
  START_TIMEOUT_MS = 10000;

var
  GCaptureLock: TCriticalSection;
  GCaptured: TMemoryStream;
  GSavedOutput: TTextRec;

{ The capture device. FPC's text-file functions are procedures that report
  errors through InOutRes; Delphi's are functions returning the error code. }

{$IFDEF FPC}
procedure CaptureWrite(var F: TTextRec);
{$ELSE}
function CaptureWrite(var F: TTextRec): Integer;
{$ENDIF}
begin
  if F.BufPos > 0 then
  begin
    GCaptureLock.Enter;
    try
      GCaptured.WriteBuffer(F.BufPtr^, F.BufPos);
    finally
      GCaptureLock.Leave;
    end;
  end;
  F.BufPos := 0;
  {$IFNDEF FPC}
  Result := 0;
  {$ENDIF}
end;

{$IFDEF FPC}
procedure CaptureClose(var F: TTextRec);
begin
end;
{$ELSE}
function CaptureClose(var F: TTextRec): Integer;
begin
  Result := 0;
end;
{$ENDIF}

{$IFDEF FPC}
procedure CaptureNoFlush(var F: TTextRec);
begin
end;
{$ELSE}
function CaptureNoFlush(var F: TTextRec): Integer;
begin
  Result := 0;
end;
{$ENDIF}

{$IFDEF FPC}
procedure CaptureOpen(var F: TTextRec);
{$ELSE}
function CaptureOpen(var F: TTextRec): Integer;
{$ENDIF}
begin
  F.InOutFunc := @CaptureWrite;
  F.FlushFunc := @CaptureNoFlush; // like a file or a pipe: Writeln doesn't flush
  F.CloseFunc := @CaptureClose;
  F.BufPos := 0;
  F.BufEnd := 0;
  {$IFNDEF FPC}
  Result := 0;
  {$ENDIF}
end;

// Points T at the capture device. T's previous contents are overwritten, not
// closed: the caller saves them first if it needs them back.
procedure RedirectToCapture(var T: Text);
begin
  AssignFile(T, '');
  TTextRec(T).OpenFunc := @CaptureOpen;
  Rewrite(T);
end;

procedure BeginCapture;
begin
  GCaptured.Clear;
  Move(Output, GSavedOutput, SizeOf(TTextRec));
  RedirectToCapture(Output);
end;

// Closes the capture (sending what is left in the buffer), gives the main
// thread its Output back and returns what was written.
function EndCapture: string;
var
  LBytes: AnsiString;
begin
  CloseFile(Output);
  Move(GSavedOutput, Output, SizeOf(TTextRec));
  SetString(LBytes, PAnsiChar(GCaptured.Memory), GCaptured.Size);
  Result := string(LBytes);
end;

type
  { Writes LINES_PER_WRITER numbered lines, alternating the two overloads,
    once AStart is set. }
  TWriterThread = class(TThread)
  private
    FIndex: Integer;
    FStart: TEvent;
    FBody: string;
  protected
    procedure Execute; override;
  public
    constructor Create(AIndex: Integer; AStart: TEvent);
  end;

constructor TWriterThread.Create(AIndex: Integer; AStart: TEvent);
begin
  FIndex := AIndex;
  FStart := AStart;
  FBody := StringOfChar(Chr(Ord('A') + AIndex), LINE_WIDTH);
  FreeOnTerminate := False;
  inherited Create(False);
end;

procedure TWriterThread.Execute;
var
  I: Integer;
begin
  {$IFDEF FPC}
  // Output is this thread's own on FPC (unit header)
  RedirectToCapture(Output);
  try
  {$ENDIF}
    if FStart.WaitFor(START_TIMEOUT_MS) <> wrSignaled then
      raise Exception.Create('start event not set');
    for I := 1 to LINES_PER_WRITER do
      if Odd(I) then
        SafeWriteln(Format('T%d-%.5d-', [FIndex, I]) + FBody)
      else
        SafeWriteln('T%d-%.5d-%s', [FIndex, I, FBody]);
  {$IFDEF FPC}
  finally
    CloseFile(Output);
  end;
  {$ENDIF}
end;

// Checks that AText holds exactly the lines the writers wrote: each one whole,
// none missing, each writer's in order. Returns '' or what is wrong.
function CheckWriterLines(const AText: string): string;
var
  LLines: TStringList;
  LNext: array[0..NUM_WRITERS - 1] of Integer;
  LLine: string;
  I, LWriter: Integer;
begin
  Result := '';
  for I := 0 to NUM_WRITERS - 1 do
    LNext[I] := 1;
  LLines := TStringList.Create;
  try
    LLines.Text := AText;
    for I := 0 to LLines.Count - 1 do
    begin
      LLine := LLines[I];
      LWriter := -1;
      if (Length(LLine) > 2) and (LLine[2] >= '0') and
        (LLine[2] < Chr(Ord('0') + NUM_WRITERS)) then
        LWriter := Ord(LLine[2]) - Ord('0');
      if (LWriter < 0) or (LNext[LWriter] > LINES_PER_WRITER) or
        (LLine <> Format('T%d-%.5d-', [LWriter, LNext[LWriter]]) +
          StringOfChar(Chr(Ord('A') + LWriter), LINE_WIDTH)) then
      begin
        Result := Format('line %d of %d is not the next line of any writer: "%s"',
          [I + 1, LLines.Count, Copy(LLine, 1, 40)]);
        Exit;
      end;
      Inc(LNext[LWriter]);
    end;
    for I := 0 to NUM_WRITERS - 1 do
      if LNext[I] <> LINES_PER_WRITER + 1 then
      begin
        Result := Format('writer %d: %d of %d lines arrived',
          [I, LNext[I] - 1, LINES_PER_WRITER]);
        Exit;
      end;
  finally
    LLines.Free;
  end;
end;

{ TSafeLogTests }

procedure TSafeLogTests.WritesTheLine;
var
  LOldIsConsole: Boolean;
  LText: string;
begin
  LOldIsConsole := IsConsole;
  IsConsole := True;
  BeginCapture;
  try
    SafeWriteln('hello world');
    SafeWriteln('');
  finally
    LText := EndCapture;
    IsConsole := LOldIsConsole;
  end;
  TAssert.AssertEquals('hello world' + sLineBreak + sLineBreak, LText);
end;

procedure TSafeLogTests.FormatOverload_FormatsTheLine;
var
  LOldIsConsole: Boolean;
  LText: string;
begin
  LOldIsConsole := IsConsole;
  IsConsole := True;
  BeginCapture;
  try
    SafeWriteln('%s=%d', ['answer', 42]);
    SafeWriteln('plain');
  finally
    LText := EndCapture;
    IsConsole := LOldIsConsole;
  end;
  TAssert.AssertEquals('answer=42' + sLineBreak + 'plain' + sLineBreak, LText);
end;

procedure TSafeLogTests.NoConsole_WritesNothing;
var
  LOldIsConsole: Boolean;
  LText: string;
begin
  LOldIsConsole := IsConsole;
  IsConsole := False;
  BeginCapture;
  try
    SafeWriteln('should not appear');
    SafeWriteln('%s', ['should not appear']);
  finally
    LText := EndCapture;
    IsConsole := LOldIsConsole;
  end;
  TAssert.AssertEquals('', LText);
end;

procedure TSafeLogTests.NoConsole_FormatOverloadDoesntFormat;
var
  LOldIsConsole: Boolean;
begin
  LOldIsConsole := IsConsole;
  IsConsole := False;
  try
    // formatting this raises EConvertError, so getting past it proves the
    // IsConsole check comes first
    SafeWriteln('%d', ['not a number']);
  finally
    IsConsole := LOldIsConsole;
  end;
  TAssert.AssertTrue('returned without formatting', True);
end;

procedure TSafeLogTests.ConcurrentWriters_EveryLineWholeAndInOrder;
var
  LOldIsConsole: Boolean;
  LStart: TEvent;
  LWriters: array[0..NUM_WRITERS - 1] of TWriterThread;
  LErrors, LText: string;
  I: Integer;
begin
  LErrors := '';
  LOldIsConsole := IsConsole;
  IsConsole := True;
  FillChar(LWriters, SizeOf(LWriters), 0);
  LStart := TEvent.Create(nil, True, False, '');
  BeginCapture;
  try
    for I := 0 to NUM_WRITERS - 1 do
      LWriters[I] := TWriterThread.Create(I, LStart);
    LStart.SetEvent;
  finally
    for I := 0 to NUM_WRITERS - 1 do
      if LWriters[I] <> nil then
      begin
        LWriters[I].WaitFor;
        if LWriters[I].FatalException <> nil then
          LErrors := LErrors + Format('writer %d: %s; ',
            [I, Exception(LWriters[I].FatalException).Message]);
        LWriters[I].Free;
      end;
    LText := EndCapture;
    IsConsole := LOldIsConsole;
    LStart.Free;
  end;
  TAssert.AssertEquals('', LErrors);
  TAssert.AssertEquals('', CheckWriterLines(LText));
end;

initialization
  GCaptureLock := TCriticalSection.Create;
  GCaptured := TMemoryStream.Create;
  TDUnitX.RegisterTestFixture(TSafeLogTests);

finalization
  GCaptured.Free;
  GCaptureLock.Free;

end.
