unit PascalCommon.VersionTests;

{ Tests for PascalCommon.Version: the numeric version agrees with its parts
  and with the version string, and the compile-time minimum-version check a
  consumer writes works as documented.

  The check is exercised by this very unit: it compiles only because the
  condition below is false. Raising the number above the current version must
  stop the build with the FATAL message (checked by hand when the mechanism
  was introduced, 2026-10-04, on FPC 3.2.2).

  DUnitX master: the FPCUnit mirror in tests/Unit/fpc is generated by
  tools/gen_fpc_mirror.py. }

interface

uses
  DUnitX.TestFramework,
  PascalCommon.DUnitXCompat,
  SysUtils,
  PascalCommon.Version;

{$IF PASCALCOMMON_VERSION < 100}
  {$MESSAGE FATAL 'PascalCommon.VersionTests needs pascal-common-faa 0.1.0 or later'}
{$IFEND}

type
  [TestFixture]
  TVersionTests = class
  public
    [Test] procedure Number_MatchesParts;
    [Test] procedure String_MatchesParts;
  end;

implementation

procedure TVersionTests.Number_MatchesParts;
begin
  TAssert.AssertEquals(
    PASCALCOMMON_VERSION_MAJOR * 10000 + PASCALCOMMON_VERSION_MINOR * 100 +
    PASCALCOMMON_VERSION_PATCH, PASCALCOMMON_VERSION);
end;

procedure TVersionTests.String_MatchesParts;
begin
  TAssert.AssertEquals(
    Format('%d.%d.%d', [PASCALCOMMON_VERSION_MAJOR, PASCALCOMMON_VERSION_MINOR,
      PASCALCOMMON_VERSION_PATCH]), PASCALCOMMON_VERSION_STRING);
end;

initialization
  TDUnitX.RegisterTestFixture(TVersionTests);

end.
